force-app/main/default/objects/Google_Calendar__c/Google_Calendar__c.object-meta.xml
<CustomObject>
    <label>Google Calendar</label>
    <nameField>
        <displayFormat>GC-{000000}</displayFormat>
        <label>Google Calendar No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Google Calendar</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Google_Calendar__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Google_Calendars</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Google_Calendar__c/fields/Calendar_Name__c.field-meta.xml
<CustomField>
    <fullName>Calendar_Name__c</fullName>
    <label>Calendar Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Google_Calendar__c/fields/Calendar_Type__c.field-meta.xml
<CustomField>
    <fullName>Calendar_Type__c</fullName>
    <inlineHelpText>Shift Calendar - for Shifts of resource
Booking Calendar - for Booking Appointments</inlineHelpText>
    <label>Calendar Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Shift Calendar</fullName>
            </value>
            <value>
                <fullName>Booking Calendar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Google_Calendar__c/fields/Google_Calendar_Id__c.field-meta.xml
<CustomField>
    <fullName>Google_Calendar_Id__c</fullName>
    <externalId>true</externalId>
    <label>Google Calendar Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Google_Calendar__c/fields/PMA_Product__c.field-meta.xml
<CustomField>
    <fullName>PMA_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PMA Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipName>Google_Calendars</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Google_Calendar__c/fields/TimeZone__c.field-meta.xml
<CustomField>
    <fullName>TimeZone__c</fullName>
    <label>TimeZone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>America/Asuncion</fullName>
            </value>
            <value>
                <fullName>Asia/Kolkata</fullName>
            </value>
            <value>
                <fullName>America/Los_Angeles</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Google_Booking_Calendar_Id__c.field-meta.xml
<CustomField>
    <fullName>Google_Booking_Calendar_Id__c</fullName>
    <inlineHelpText>Google Booking Calendar External Id</inlineHelpText>
    <label>Google Booking Calendar Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Google_Shift_Calendar_Id__c.field-meta.xml
<CustomField>
    <fullName>Google_Shift_Calendar_Id__c</fullName>
    <inlineHelpText>Google Shift Calendar External Id</inlineHelpText>
    <label>Google Shift Calendar Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/TimeZone__c.field-meta.xml
<CustomField>
    <fullName>TimeZone__c</fullName>
    <label>TimeZone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>America/Asuncion</fullName>
            </value>
            <value>
                <fullName>Asia/Kolkata</fullName>
            </value>
            <value>
                <fullName>America/Los_Angeles</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MapProductWithGoogleCalendar.cls
public with sharing class MapProductWithGoogleCalendar {

    @AuraEnabled
    public static Product__c getProductDetails(Id productRecordId) {
        Product__c prodRecord = new Product__c();
        try {
            String fetchSchedulingProductQuery = 'SELECT ' + SYS_Helper.getAllFieldsFor('Product__c') +
            ', ' + SYS_Helper.getAllParentFields('Account__r.', 'Account') +
            ' FROM Product__c WHERE Id =: productRecordId';
            List<Product__c> fetchSchedulingProductDetails = Database.query(fetchSchedulingProductQuery);
            prodRecord = (fetchSchedulingProductDetails.size() > 0) ? fetchSchedulingProductDetails[0] : new Product__c();
            return prodRecord;
        } catch (Exception ex) {
            throw new AuraHandledException(ex.getMessage());
        }
    }

    @AuraEnabled
    public static List<Google_Calendar__c> ListofCalendars(Boolean isAccountBasedMapper, String accountRecordId) {
        String filterAccount = '';
        if(isAccountBasedMapper && String.isNotBlank(accountRecordId)){
            filterAccount = ' AND Account__c =: accountRecordId';
        }
        String fetchgoogleCalendarListQuery = 'SELECT ' + SYS_Helper.getAllFieldsFor('Google_Calendar__c') +
            ', ' + SYS_Helper.getAllParentFields('Account__r.', 'Account') +
            ', ' + SYS_Helper.getAllParentFields('PMA_Product__r.', 'Product__c') +
            ' FROM Google_Calendar__c WHERE Google_Calendar_Id__c != NULL' + filterAccount;
        List<Google_Calendar__c> googleCalendarList = Database.query(fetchgoogleCalendarListQuery);
        return googleCalendarList;
    }

    @AuraEnabled
    public static Product__c updateProductWithCalendarKey( String calendarType, String productId, String calendarSysKey, String calendarId ) {
        try {
            Product__c updateProductRecord = new Product__c();
            updateProductRecord.Id = productId;
            if(calendarType == 'Shift'){
                updateProductRecord.Google_Shift_Calendar_Id__c = calendarSysKey;
                update updateProductRecord;
            }
            if(calendarType == 'Booking'){
                updateProductRecord.Google_Booking_Calendar_Id__c = calendarSysKey;
                update updateProductRecord;
            }           
            Product__c fetchProductRecord = getProductDetails(productId);
            return fetchProductRecord;
        } catch (Exception ex) {
            throw new AuraHandledException(ex.getMessage());
        }
    }

    @AuraEnabled
    public static Google_Calendar__c createCustomCalendar(Boolean isAccountBasedMapper, String accountRecordId, String calendarName, String productId, String calendarType, String configTimeZone){
        try {
            Google_Calendar__c googleCalendarRecord = new Google_Calendar__c();
            googleCalendarRecord.Calendar_Name__c = calendarName;
            googleCalendarRecord.PMA_Product__c = productId;
            googleCalendarRecord.Calendar_Type__c = calendarType;
            googleCalendarRecord.TimeZone__c = configTimeZone;
            // googleCalendarRecord.Active__c = false;
            if(isAccountBasedMapper && String.isNotBlank(accountRecordId)){
                googleCalendarRecord.Account__c = accountRecordId;
            }
            insert googleCalendarRecord;
            return googleCalendarRecord;
        } catch (Exception ex) {
            throw new AuraHandledException(ex.getMessage());
        }
    }  
}