force-app/main/default/objects/Appointment_Scheduling__c/Appointment_Scheduling__c.object-meta.xml
<CustomObject>
    <label>Appointment Scheduling</label>
    <nameField>
        <label>Appointment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Appointment Scheduling</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Appointment_Scheduling__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Appointment Scheduling</relationshipLabel>
    <relationshipName>Appointment_Scheduling</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appointment_Scheduling__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Appointment Scheduling</relationshipLabel>
    <relationshipName>Appointment_Scheduling</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appointment_Scheduling__c/fields/Duration_of_Meet__c.field-meta.xml
<CustomField>
    <fullName>Duration_of_Meet__c</fullName>
    <label>Duration of Meet</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Appointment_Scheduling__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <label>EndDate</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Appointment_Scheduling__c/fields/Google_Booking_Calendar_Id__c.field-meta.xml
<CustomField>
    <fullName>Google_Booking_Calendar_Id__c</fullName>
    <inlineHelpText>Google Booking Calendar External Id</inlineHelpText>
    <label>Google Booking Calendar Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Appointment_Scheduling__c/fields/Google_Calendar_Event_Id__c.field-meta.xml
<CustomField>
    <fullName>Google_Calendar_Event_Id__c</fullName>
    <externalId>true</externalId>
    <label>Google Calendar Event Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Appointment_Scheduling__c/fields/Guest_Email__c.field-meta.xml
<CustomField>
    <fullName>Guest_Email__c</fullName>
    <label>Guest Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Appointment_Scheduling__c/fields/hangoutLink__c.field-meta.xml
<CustomField>
    <fullName>hangoutLink__c</fullName>
    <label>hangoutLink</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Appointment_Scheduling__c/fields/ISActive__c.field-meta.xml
<CustomField>
    <fullName>ISActive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ISActive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Appointment_Scheduling__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Scheduled Appointments</relationshipLabel>
    <relationshipName>Scheduled_Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appointment_Scheduling__c/fields/Scheduled_User_TimeZone__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_User_TimeZone__c</fullName>
    <label>Scheduled User TimeZone</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Appointment_Scheduling__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <label>StartDate</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Appointment_Scheduling__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>confirmed</fullName>
            </value>
            <value>
                <fullName>Notconfirmed</fullName>
                <default>true</default>
                <label>Notconfirmed</label>
            </value>
            <value>
                <fullName>proposed</fullName>
            </value>
            <value>
                <fullName>pending</fullName>
            </value>
            <value>
                <fullName>booked</fullName>
            </value>
            <value>
                <fullName>arrived</fullName>
            </value>
            <value>
                <fullName>fulfilled</fullName>
            </value>
            <value>
                <fullName>cancelled</fullName>
            </value>
            <value>
                <fullName>noshow</fullName>
            </value>
            <value>
                <fullName>entered-in-error</fullName>
            </value>
            <value>
                <fullName>checked-in</fullName>
            </value>
            <value>
                <fullName>waitlist</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Appointment_Scheduling__c/fields/TimeZone__c.field-meta.xml
<CustomField>
    <fullName>TimeZone__c</fullName>
    <label>TimeZone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>America/Asuncion</fullName>
            </value>
            <value>
                <fullName>Asia/Kolkata</fullName>
            </value>
            <value>
                <fullName>America/Los_Angeles</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Google_Booking_Calendar_Id__c.field-meta.xml
<CustomField>
    <fullName>Google_Booking_Calendar_Id__c</fullName>
    <inlineHelpText>Google Booking Calendar External Id</inlineHelpText>
    <label>Google Booking Calendar Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/TimeZone__c.field-meta.xml
<CustomField>
    <fullName>TimeZone__c</fullName>
    <label>TimeZone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>America/Asuncion</fullName>
            </value>
            <value>
                <fullName>Asia/Kolkata</fullName>
            </value>
            <value>
                <fullName>America/Los_Angeles</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <externalId>true</externalId>
    <label>UUID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/AppointmentSchedulingService.cls
public without sharing class AppointmentSchedulingService {

    public static Appointment_Scheduling__c getAppointmentDetails(String IdorUuid) {
        String appointmentListFilterCriteria = ' WHERE ';
        if ((IdorUuid.length() == 15) || (IdorUuid.length() == 18)) {
            appointmentListFilterCriteria += 'Id =: IdorUuid';
        } else {
            appointmentListFilterCriteria += 'UUID__c =: IdorUuid';
        }
        String appointmentListQuery = 'SELECT ' + SYS_Helper.getAllFieldsFor('Appointment_Scheduling__c') +
                ', ' + SYS_Helper.getAllParentFields('Account__r.', 'Account') +
                ', ' + SYS_Helper.getAllParentFields('Product__r.', 'Product__c') +
                ' FROM Appointment_Scheduling__c'+ appointmentListFilterCriteria;
        List<Appointment_Scheduling__c> appointmentList = Database.query(appointmentListQuery);
        return (appointmentList.size() > 0) ? appointmentList[0] : new Appointment_Scheduling__c();
    }

    public static Boolean hasDuplicateAppointments(Datetime appointmentStartDateTime, String Google_Booking_Calendar_Id) {
        String appointmentListQuery = 'SELECT ' + SYS_Helper.getAllFieldsFor('Appointment_Scheduling__c') +
                ', ' + SYS_Helper.getAllParentFields('Account__r.', 'Account') +
                ', ' + SYS_Helper.getAllParentFields('Product__r.', 'Product__c') +
                ' FROM Appointment_Scheduling__c WHERE StartDate__c =: appointmentStartDateTime AND Google_Booking_Calendar_Id__c =: Google_Booking_Calendar_Id AND Status__c = \'confirmed\'';
        List<Appointment_Scheduling__c> appointmentList = Database.query(appointmentListQuery);
        return (appointmentList.size() >= THRESHOLD);
    }

    public static Integer THRESHOLD{
        get{
            Integer val;
            try {
                val = Integer.valueOf(Label.ADS_booking_threshold);
            } catch (Exception e) {
                val = 1;
            }
            return val;
        }
    }

    public static Appointment_Scheduling__c createNewAppointment(
        String appointmentTitle,
        Datetime appointmentStartDateTime,
        Datetime appointmentEndDateTime,
        String meetDuration,
        String appointmentDescription,
        Id accountId,
        Id contactId,
        Id productId,
        String emails,
        String bookingcalendarId,
        String googleCalendarEventId,
        String googleCalendarEventStatus,
        String googleCalendarEventTimezone,
        String scheduledUserTimezone, Boolean IsActive) {

        //Name Field MAX Size Truncate
        Integer fieldmaxSize = 80;
        String truncatedAppointmentTitle = appointmentTitle;
        if (appointmentTitle.length() > fieldmaxSize) {
            truncatedAppointmentTitle = appointmentTitle.substring(0, fieldmaxSize);
        }
        Date appointmentDate = Date.newinstance(appointmentStartDateTime.year(), appointmentStartDateTime.month(), appointmentStartDateTime.day());
        Appointment_Scheduling__c googleCalendarEvent = new Appointment_Scheduling__c(
            Name = truncatedAppointmentTitle,
            AppointmentDate__c = appointmentDate,
            StartDate__c = appointmentStartDateTime,
            EndDate__c = appointmentEndDateTime,
            Duration_of_Meet__c = meetDuration,
            Description__c = appointmentDescription,
            Account__c = accountId,
            Contact__c = contactId,
            Product__c = productId,
            Guest_Email__c = emails,
            Google_Booking_Calendar_Id__c = bookingcalendarId,
            Google_Calendar_Event_Id__c = googleCalendarEventId,
            Status__c = googleCalendarEventStatus,
            TimeZone__c = googleCalendarEventTimezone,
            Scheduled_User_TimeZone__c = scheduledUserTimezone,
            ISActive__c = IsActive,
            UUID__c = SYS_Helper.getUUID()
        );

        insert googleCalendarEvent;

        return getAppointmentDetails(googleCalendarEvent.Id);
    }
    public static Appointment_Scheduling__c createNewAppointmenthangoutlink(
        String appointmentTitle,
        Datetime appointmentStartDateTime,
        Datetime appointmentEndDateTime,
        String meetDuration,
        String appointmentDescription,
        Id accountId,
        Id contactId,
        Id productId,
        String emails,
        String bookingcalendarId,
        String googleCalendarEventId,
        String googleCalendarEventStatus,
        String googleCalendarEventTimezone,
        String scheduledUserTimezone, Boolean IsActive,string handoutMeetingURL) {

        //Name Field MAX Size Truncate
        Integer fieldmaxSize = 80;
        String truncatedAppointmentTitle = appointmentTitle;
        if (appointmentTitle.length() > fieldmaxSize) {
            truncatedAppointmentTitle = appointmentTitle.substring(0, fieldmaxSize);
        }
        Date appointmentDate = Date.newinstance(appointmentStartDateTime.year(), appointmentStartDateTime.month(), appointmentStartDateTime.day());
        Appointment_Scheduling__c googleCalendarEvent = new Appointment_Scheduling__c(
            Name = truncatedAppointmentTitle,
            AppointmentDate__c = appointmentDate,
            StartDate__c = appointmentStartDateTime,
            EndDate__c = appointmentEndDateTime,
            Duration_of_Meet__c = meetDuration,
            Description__c = appointmentDescription,
            Account__c = accountId,
            Contact__c = contactId,
            Product__c = productId,
            Guest_Email__c = emails,
            Google_Booking_Calendar_Id__c = bookingcalendarId,
            Google_Calendar_Event_Id__c = googleCalendarEventId,
            Status__c = googleCalendarEventStatus,
            TimeZone__c = googleCalendarEventTimezone,
            Scheduled_User_TimeZone__c = scheduledUserTimezone,
            ISActive__c = IsActive,
            UUID__c = SYS_Helper.getUUID(),
            hangoutLink__c = handoutMeetingURL
        );

        insert googleCalendarEvent;

        return getAppointmentDetails(googleCalendarEvent.Id);
    }
    public static Appointment_Scheduling__c updateAppointment(Appointment_Scheduling__c updateAppointmentRecord){
        if(updateAppointmentRecord != null){
            update updateAppointmentRecord;
        }
        return getAppointmentDetails(updateAppointmentRecord.Id);
    }

}