force-app/main/default/objects/Appointment_Scheduling__c/Appointment_Scheduling__c.object-meta.xml
<CustomObject>
    <label>Appointment Scheduling</label>
    <nameField>
        <label>Appointment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Appointment Scheduling</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Appointment_Scheduling__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Appointment Scheduling</relationshipLabel>
    <relationshipName>Appointment_Scheduling</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appointment_Scheduling__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Appointment Scheduling</relationshipLabel>
    <relationshipName>Appointment_Scheduling</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appointment_Scheduling__c/fields/LocationTags__c.field-meta.xml
<CustomField>
    <fullName>LocationTags__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>LocationTags</label>
    <referenceTo>LocationTags__c</referenceTo>
    <relationshipLabel>Appointment Scheduling</relationshipLabel>
    <relationshipName>Appointment_Scheduling</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appointment_Scheduling__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Scheduled Appointments</relationshipLabel>
    <relationshipName>Scheduled_Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appointment_Scheduling__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <label>StartDate</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Appointment_Scheduling__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>confirmed</fullName>
            </value>
            <value>
                <fullName>Notconfirmed</fullName>
                <default>true</default>
                <label>Notconfirmed</label>
            </value>
            <value>
                <fullName>proposed</fullName>
            </value>
            <value>
                <fullName>pending</fullName>
            </value>
            <value>
                <fullName>booked</fullName>
            </value>
            <value>
                <fullName>arrived</fullName>
            </value>
            <value>
                <fullName>fulfilled</fullName>
            </value>
            <value>
                <fullName>cancelled</fullName>
            </value>
            <value>
                <fullName>noshow</fullName>
            </value>
            <value>
                <fullName>entered-in-error</fullName>
            </value>
            <value>
                <fullName>checked-in</fullName>
            </value>
            <value>
                <fullName>waitlist</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <externalId>true</externalId>
    <label>UUID</label>
    <length>250</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/LocationTags__c/LocationTags__c.object-meta.xml
<CustomObject>
    <label>LocationTags</label>
    <nameField>
        <label>LocationTags Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LocationTags</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LocationTags__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>LocationTags</relationshipLabel>
    <relationshipName>LocationTags</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <externalId>true</externalId>
    <label>UUID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/CheckinController.cls
public without sharing class CheckinController {

    public String uuid { get; set; }
    public Appointment_Scheduling__c appointment { get; set; }
    public String locationTagUUID { get; set; }
    public String checkinMessage { get; set; }
    public Datetime appointmentStartTime { get; set; }
    public String appointmentStartTimeString { get; set; }
    public String invalidUrlMessage { get; set; }
    public Boolean isComponent { get; set; }
    public ToDo__c todorecord { get; set; }



    public CheckinController() { }

    public class CheckinControllerException extends Exception {}

    public void init() {
        try {
            this.uuid = ApexPages.currentPage().getParameters().get('uuid');
            this.appointment = getAppointmentDetails(this.uuid);
            if (this.appointment != NULL) {
                this.appointmentStartTime = this.appointment?.StartDate__c;
                if (this.appointment?.Status__c == 'checked-in') {
                    this.checkinMessage = 'Checked in successfully!!';
                }
            }
            else {
                this.invalidUrlMessage = 'Invalid URL!!';
            }
        } catch ( Exception e ) {
            System.debug(e.getMessage()+'\n'+e.getStackTraceString());
            throw new CheckinControllerException(e.getMessage()+'\n'+e.getStackTraceString());
        }
    }

    public void checkinAppointment() {
        try {
            System.debug('locationTagUUID '+locationTagUUID);
            LocationTags__c locationtag;
            if (String.isNotBlank(locationTagUUID))
                locationtag = getLocationTag(locationTagUUID);

            if (appointment != NULL) {
                appointment.LocationTags__c = locationtag?.Id;
                appointment.Status__c = 'checked-in';
                System.debug('appointment '+appointment);
                update appointment;
                this.checkinMessage = 'Checked in successfully!!';
            }
            if (this.todorecord != NULL) {
                this.todorecord.Status__c = 'Completed';
                update this.todorecord;
            }
            
        } catch ( Exception e ) {
            System.debug(e.getMessage()+'\n'+e.getStackTraceString());
            throw new CheckinControllerException(e.getMessage()+'\n'+e.getStackTraceString());
        }
    }

    public LocationTags__c getLocationTag(String uuid) {
        LocationTags__c record;
        try {
            String query = 'SELECT '+ SYS_Helper.getAllFieldsFor('LocationTags__c') 
                    +' FROM LocationTags__c ';
            String whereclause = ' WHERE UUID__c =:uuid LIMIT 1';

            List<LocationTags__c> records = Database.query(String.escapeSingleQuotes(query + whereclause));
            if (records.size() > 0) 
            record = records[0];

        } catch ( Exception e ) {
            System.debug(e.getMessage()+'\n'+e.getStackTraceString());
            throw new CheckinControllerException(e.getMessage()+'\n'+e.getStackTraceString());
        }
        return record;
    }

    public Appointment_Scheduling__c getAppointmentDetails(String uuid) {
        Appointment_Scheduling__c record;
        try {
            String query = 'SELECT '+ SYS_Helper.getAllFieldsFor('Appointment_Scheduling__c') 
                    +', '+ SYS_Helper.getAllParentFields('Account__r.', 'Account') 
                    +', '+ SYS_Helper.getAllParentFields('Contact__r.', 'Contact') 
                    +', '+ SYS_Helper.getAllParentFields('Product__r.', 'Product__c')
                    +' FROM Appointment_Scheduling__c ';
            String whereclause = ' WHERE UUID__c =:uuid LIMIT 1';

            List<Appointment_Scheduling__c> records = Database.query(String.escapeSingleQuotes(query + whereclause));
            if (records.size() > 0) 
                record = records[0];

        } catch ( Exception e ) {
            System.debug(e.getMessage()+'\n'+e.getStackTraceString());
            throw new CheckinControllerException(e.getMessage()+'\n'+e.getStackTraceString());
        }
        return record;
    }
}