force-app/main/default/objects/Appointment_Scheduling__c/Appointment_Scheduling__c.object-meta.xml
<CustomObject>
    <label>Appointment Scheduling</label>
    <nameField>
        <label>Appointment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Appointment Scheduling</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Appointment_Scheduling__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Appointment Scheduling</relationshipLabel>
    <relationshipName>Appointment_Scheduling</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appointment_Scheduling__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Scheduled Appointments</relationshipLabel>
    <relationshipName>Scheduled_Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appointment_Scheduling__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <label>StartDate</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Appointment_Scheduling__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>confirmed</fullName>
            </value>
            <value>
                <fullName>Notconfirmed</fullName>
                <default>true</default>
                <label>Notconfirmed</label>
            </value>
            <value>
                <fullName>proposed</fullName>
            </value>
            <value>
                <fullName>pending</fullName>
            </value>
            <value>
                <fullName>booked</fullName>
            </value>
            <value>
                <fullName>arrived</fullName>
            </value>
            <value>
                <fullName>fulfilled</fullName>
            </value>
            <value>
                <fullName>cancelled</fullName>
            </value>
            <value>
                <fullName>noshow</fullName>
            </value>
            <value>
                <fullName>entered-in-error</fullName>
            </value>
            <value>
                <fullName>checked-in</fullName>
            </value>
            <value>
                <fullName>waitlist</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Balance_Transaction__c/Balance_Transaction__c.object-meta.xml
<CustomObject>
    <label>Balance Transaction</label>
    <nameField>
        <displayFormat>AT-{000000}</displayFormat>
        <label>Transaction Reference No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Balance Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Balance_Transaction__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Balance Transactions</relationshipLabel>
    <relationshipName>Balance_Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/EligibulityUtility.cls
public without sharing class EligibulityUtility {
   /*********************************************************************
   * ***********************************************************
   * This Hook is for getting the Details of Insurance Details From By using the 
   * Recordid and with additional filters.
   */
  
  public static list < Insurance__c > insuranceDataUtility(string contactRecordId) {
    List < Insurance__c > InsurenceList = new list < Insurance__c > ();
    //List <Appointment_Scheduling__c> AppointmentList = new list <Appointment_Scheduling__c>();
    try {
      String insurencestring = 'SELECT ' + SYS_Helper.getAllFieldsFor('Insurance__c') +
        ', ' + SYS_Helper.getAllParentFields('Contact__r.', 'Contact') +
        ', ( SELECT ' + SYS_Helper.getAllFieldsFor('Copay__c') + ' FROM Copay__r)' +
        ' FROM Insurance__c WHERE (Contact__c =: contactRecordId)';
      system.debug('members serch' + insurencestring);
      InsurenceList = Database.query(insurencestring);
      system.debug('fetchRecordNDR' + InsurenceList);

    } catch (Exception e) {
      System.debug('The following exception has occurred: ' + e.getMessage());
    }
    return (InsurenceList.size() > 0) ? (InsurenceList) : (new List < Insurance__c > ());
  }
  /*********************************************************************
   * ***********************************************************
   * This Hook is for getting the Details of Appointment From By using the 
   * Recordid and with additional filters.
   */
  public static  Appointment_Scheduling__c  AppointmentDataUtility(string contactRecordId , string AppointmentId) {
   // List < Appointment_Scheduling__c > AppointmentList = new list < Appointment_Scheduling__c > ();
   Appointment_Scheduling__c  Appointment;
    try {

      string Appointmentstring = 'SELECT ' + SYS_Helper.getAllFieldsFor('Appointment_Scheduling__c') +
        ', ' + SYS_Helper.getAllParentFields('Product__r.', 'Product__c') +
        ' FROM Appointment_Scheduling__c WHERE (StartDate__c >=today) AND (Contact__c =: contactRecordId) AND (Id =: AppointmentId)';
      system.debug('Appointmentstring NDR' + Appointmentstring);
      Appointment = Database.query(Appointmentstring);
      system.debug('Appointmentstring NDR' + Appointment);
    } catch (Exception e) {
      System.debug('The following exception has occurred: ' + e.getMessage());
    }
    return (Appointment != null) ? (Appointment) : (new Appointment_Scheduling__c ());
  }

  public static Insurance__c copayCheckUtility(List < Insurance__c > insuranceList, string insuranceId) {
    Map < Id, Insurance__c > insuranceMap = new Map < Id, Insurance__c > ();
    for (Insurance__c insuranceiter: insuranceList) {
      insuranceMap.put(insuranceiter.Id, insuranceiter);

    }
    Insurance__c insurance = insuranceMap.get(insuranceId);
    system.debug('insurance NDR ' + insurance);
    return insurance;
  }
  /*********************************************************************
   * ***********************************************************
   * This Hook is for Adding Balance record and marking the todo as complete
   */
  public static ToDo__c todoCompleteUtility(string todorecordId, Decimal Amount, string memberrecordid) {
    system.debug('todorecordId' + todorecordId);
    List < Appointment_Scheduling__c > AppointmentList = new list < Appointment_Scheduling__c > ();
    String Appointmentstring = 'SELECT ' + SYS_Helper.getAllFieldsFor('Appointment_Scheduling__c') +
      ', ' + SYS_Helper.getAllParentFields('Product__r.', 'Product__c') +
      ' FROM Appointment_Scheduling__c WHERE (Contact__c =: memberrecordid) AND Status__c=\'Status__c\'';
    system.debug('members serch' + Appointmentstring);
    AppointmentList = Database.query(Appointmentstring);
    system.debug('members serch' + AppointmentList);
    Balance_Transaction__c BalanceTransaction = new Balance_Transaction__c();
    BalanceTransaction.Type__c = 'Debit';
    BalanceTransaction.Amount__c = Amount;
    BalanceTransaction.Contact__c = memberrecordid;
    insert BalanceTransaction;
    ToDo__c todorec = [SELECT Status__c From ToDo__c WHERE Id =: todorecordId];
    todorec.Status__c = 'Completed';
    update todorec;
    return todorec;

  }

}