force-app/main/default/objects/Account/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <defaultValue>TEXT(1)</defaultValue>
    <label>Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Phone_Country_Codes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Activity__c/Activity__c.object-meta.xml
<CustomObject>
    <label>PMA Activity</label>
    <nameField>
        <displayFormat>Activity-{0}</displayFormat>
        <label>Activity#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PMA Activities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Activity__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>PMA_Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activity__c/fields/Activity_No__c.field-meta.xml
<CustomField>
    <fullName>Activity_No__c</fullName>
    <displayFormat>{0}</displayFormat>
    <label>Activity No</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Activity__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>PMA Activities</relationshipLabel>
    <relationshipName>PMA_Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activity__c/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <defaultValue>TEXT(1)</defaultValue>
    <label>Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Phone_Country_Codes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Activity__c/fields/Direction__c.field-meta.xml
<CustomField>
    <fullName>Direction__c</fullName>
    <label>Direction</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>OUTBOUND</fullName>
            </value>
            <value>
                <fullName>INBOUND</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Activity__c/fields/External_Number__c.field-meta.xml
<CustomField>
    <fullName>External_Number__c</fullName>
    <inlineHelpText>Outbound - From Plivo Number
Inbound - To Plivo Number</inlineHelpText>
    <label>External Number</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Activity__c/fields/Formatted_Phone__c.field-meta.xml
<CustomField>
    <fullName>Formatted_Phone__c</fullName>
    <label>Formatted Phone</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Activity__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>PMA Activities</relationshipLabel>
    <relationshipName>PMA_Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activity__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Queued</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Undelivered</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Skipped</fullName>
            </value>
            <value>
                <fullName>Replied</fullName>
            </value>
            <value>
                <fullName>ringing</fullName>
                <label>Ringing</label>
            </value>
            <value>
                <fullName>hangup</fullName>
                <label>Hangup</label>
            </value>
            <value>
                <fullName>connected</fullName>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>answer</fullName>
                <label>Answered</label>
            </value>
            <value>
                <fullName>Sending</fullName>
            </value>
            <value>
                <fullName>no-answer</fullName>
                <label>Not Answered</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Activity__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>sms</fullName>
            </value>
            <value>
                <fullName>mms</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Call</fullName>
            </value>
            <value>
                <fullName>Recording</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Activity__c/fields/WhatId_ObjectApi_Name__c.field-meta.xml
<CustomField>
    <fullName>WhatId_ObjectApi_Name__c</fullName>
    <label>WhatId ObjectApi Name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Latest_Activity_Number__c.field-meta.xml
<CustomField>
    <fullName>Latest_Activity_Number__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Latest Activity Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Inbox__c/Inbox__c.object-meta.xml
<CustomObject>
    <label>Inbox</label>
    <nameField>
        <displayFormat>INB-{000000}</displayFormat>
        <label>Inbox Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inbox</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Inbox__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Inbox</relationshipLabel>
    <relationshipName>Inbox</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inbox__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Inbox</relationshipLabel>
    <relationshipName>Inbox</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inbox__c/fields/External_Contact_Point__c.field-meta.xml
<CustomField>
    <fullName>External_Contact_Point__c</fullName>
    <externalId>true</externalId>
    <label>External Contact Point</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Inbox__c/fields/External_Phone__c.field-meta.xml
<CustomField>
    <fullName>External_Phone__c</fullName>
    <label>External Phone</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Inbox__c/fields/Latest_Activity_Number__c.field-meta.xml
<CustomField>
    <fullName>Latest_Activity_Number__c</fullName>
    <label>Latest Activity Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Inbox__c/fields/Latest_Message__c.field-meta.xml
<CustomField>
    <fullName>Latest_Message__c</fullName>
    <label>Latest Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Inbox__c/fields/Latest_Message_Received_At__c.field-meta.xml
<CustomField>
    <fullName>Latest_Message_Received_At__c</fullName>
    <label>Latest Message Received At</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Inbox__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Inbox</relationshipLabel>
    <relationshipName>Inbox</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inbox__c/fields/WhatId__c.field-meta.xml
<CustomField>
    <fullName>WhatId__c</fullName>
    <label>WhatId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Inbox__c/fields/WhatId_ObjectApi_Name__c.field-meta.xml
<CustomField>
    <fullName>WhatId_ObjectApi_Name__c</fullName>
    <label>WhatId ObjectApi Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <defaultValue>TEXT(1)</defaultValue>
    <label>Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Phone_Country_Codes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Phone_Country_Codes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <default>true</default>
        <label>1</label>
    </customValue>
    <description>Add SMS Integration Supported Country Codes</description>
    <masterLabel>Phone Country Codes</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ActivityTriggerHandler.cls
public without sharing class ActivityTriggerHandler {

    //Helper Method to Get Whattid
    public static String getWhattIdFromActivityRecord(Activity__c activityRecord){
        Id whattId;
        // if(activityRecord.Account__c != null){
        //     whattId = activityRecord.Account__c;
        // }
        // if(activityRecord.Lead__c != null){
        //     whattId = activityRecord.Lead__c;
        // }
        if(activityRecord.Contact__c != null){
            whattId = activityRecord.Contact__c;
        }
        whattId = String.isBlank(whattId) ? activityRecord.WhatId__c : whattId;
        return whattId;
    }

    //Helper Method to Get ContactName
    public static String getContactNameFromActivityRecord(Activity__c activityRecord){
        String memberName;
        // if(activityRecord.Account__c != null){
        //     memberName = activityRecord.Account__r.Name;
        // }
        // if(activityRecord.Lead__c != null){
        //     memberName = (String.isNotBlank(activityRecord.Lead__r.FirstName) ? activityRecord.Lead__r.FirstName : '') + '' + (String.isNotBlank(activityRecord.Lead__r.LastName) ? ' ' + activityRecord.Lead__r.LastName : '');
        // }
        if(activityRecord.Contact__c != null){
            memberName = (String.isNotBlank(activityRecord.Contact__r.FirstName) ? activityRecord.Contact__r.FirstName : '') + '' + (String.isNotBlank(activityRecord.Contact__r.LastName) ? ' ' + activityRecord.Contact__r.LastName : '');
        }
        memberName = String.isBlank(memberName) ? activityRecord.Formatted_Phone__c : memberName;
        return memberName;
    }

    //Helper Method to Get Name
    public static String getFormattedPhoneNumber(String countryCode, String unFormattedPhone){
        if(!String.isBlank(unFormattedPhone)) {
            String nondigits = '[^0-9]';
            String PhoneNumberDigitsOnly;
            Integer PhoneNumberLength = 0;
            countryCode = String.isNotBlank(countryCode) ? countryCode : System.Label.PlivoContryCode;
            
            // remove all non numeric
            PhoneNumberDigitsOnly = unFormattedPhone.replaceAll(nondigits,'');
            PhoneNumberLength = PhoneNumberDigitsOnly.length();

            if (PhoneNumberLength == 10) {
                //Add Country Code to PhoneNumber
                return  countryCode + PhoneNumberDigitsOnly;
            } else if(PhoneNumberLength == 11){
                return PhoneNumberDigitsOnly;
            } else if(PhoneNumberLength > 10){
                return countryCode + PhoneNumberDigitsOnly.substring(0,10);
            }else {
                return PhoneNumberDigitsOnly.substring(0,PhoneNumberLength);
            }            
        }
        return unFormattedPhone;
    }

    public static void handleAfterInsert() {
        List<Inbox__c> inboxList = new List<Inbox__c>();

        for(Activity__c iterActivity : ((List<Activity__c>)Trigger.new)){
            String IterContactName = getContactNameFromActivityRecord(iterActivity);
            String IterContactPhoneNumber = getFormattedPhoneNumber(iterActivity.Country_Code__c, iterActivity.Phone__c);

            String ExternalContactPoint = String.isNotBlank(IterContactPhoneNumber) ? IterContactPhoneNumber : iterActivity.Email__c;
            String latestMessage;
            if(iterActivity.Type__c  == 'sms'){
                latestMessage = iterActivity.Message__c;
            }
            else if(iterActivity.Type__c  == 'mms'){
                latestMessage = iterActivity.Direction__c + ' MMS '+ ((iterActivity.Direction__c  == 'INBOUND') ? 'From ' : 'To ') + IterContactName;
            }
            else if(iterActivity.Type__c  == 'Call'){
                latestMessage = iterActivity.Direction__c + ' Call '+ ((iterActivity.Direction__c  == 'INBOUND') ? 'From ' : 'To ') + IterContactName;
            }else{
                latestMessage = 'Say Hello!';
            }

            Inbox__c inboxRecord = new Inbox__c();
            inboxRecord.Contact__c = iterActivity.Contact__c;
            inboxRecord.Account__c = iterActivity.Account__c;
            // inboxRecord.Lead__c = iterActivity.Lead__c;
            inboxRecord.WhatId__c = iterActivity.WhatId__c;
            inboxRecord.WhatId_ObjectApi_Name__c = iterActivity.WhatId_ObjectApi_Name__c;
            inboxRecord.Latest_Message__c = latestMessage;
            inboxRecord.Latest_Message_Received_At__c = iterActivity.When__c;
            inboxRecord.Latest_Activity_Number__c = Integer.valueOf(iterActivity.Activity_No__c);

            inboxRecord.Email__c = iterActivity.Email__c;
            inboxRecord.Phone__c = IterContactPhoneNumber;
            inboxRecord.External_Phone__c = iterActivity.External_Number__c;
            inboxRecord.External_Contact_Point__c = ExternalContactPoint;
            if(String.isNotBlank(ExternalContactPoint)){
                inboxList.add(inboxRecord);
            }
        }
        if(inboxList.size() > 0) {
            Schema.SObjectField externalIdField = Inbox__c.Fields.External_Contact_Point__c;
            List<SYS_IntegrationLog__c> errorLogs = new List<SYS_IntegrationLog__c>();
            Database.UpsertResult[] srList = Database.upsert(inboxList, externalIdField, false);
            for (Database.UpsertResult sr: srList) {
                if (!sr.isSuccess()) {
                    // Operation failed, so get all errors                
                    String errMsg = 'The following error has occurred while performing DML: ';
                    for (Database.Error err: sr.getErrors()) {
                        errMsg += err.getStatusCode() + ': ' + err.getMessage() + '. Fields affected are: ' + err.getFields() + '\n';
                    }
                    SYS_IntegrationLog__c log = new SYS_IntegrationLog__c();
                    log.How_to_process__c = 'ignore_log';
                    log.Type__c = 'RESPONSE';
                    log.retry__c = false;
                    log.Status__c = 'FAIL';
                    log.Message__c = errMsg;
                    errorLogs.add(log);
                }
            }
            if(errorLogs.size() > 0){
                SYS_Helper.upsertLog(errorLogs);
            }
        }
    }

    public static void handleBeforeInsert() {
        for(Activity__c iterActivity : ((List<Activity__c>)Trigger.new)){
            String ObjectApiName;
            String IterContactPhoneNumber = getFormattedPhoneNumber(iterActivity.Country_Code__c, iterActivity.Phone__c);
            // Id IterWhattId = getWhattIdFromActivityRecord(iterActivity);
            Id IterWhattId = iterActivity.Contact__c;
            //Set Formatted Phone Number on Activity
            iterActivity.Formatted_Phone__c = IterContactPhoneNumber;
            //Set When If Its Blank
            iterActivity.When__c =  (iterActivity.When__c != null) ? iterActivity.When__c : iterActivity.CreatedDate;
            if(IterWhattId != null){
                iterActivity.WhatId__c = IterWhattId;
                ObjectApiName = IterWhattId.getSObjectType().getDescribe().getName();
                iterActivity.WhatId_ObjectApi_Name__c = ObjectApiName;
            }
        }
    }

    public static void handleBeforeUpdate() {
        Map<Id, Activity__c> oldMap  = (Map<Id, Activity__c>)Trigger.oldMap;
        for(Activity__c iterActivity : ((List<Activity__c>)Trigger.new)){
            String ObjectApiName;
            String IterContactPhoneNumber = getFormattedPhoneNumber(iterActivity.Country_Code__c, iterActivity.Phone__c);
            // Id IterWhattId = getWhattIdFromActivityRecord(iterActivity);
            Id IterWhattId = iterActivity.Contact__c;
            //Set Formatted Phone Number on Activity
            iterActivity.Formatted_Phone__c = IterContactPhoneNumber;
            //Set When If Its Blank
            iterActivity.When__c =  (iterActivity.When__c != null) ? iterActivity.When__c : iterActivity.CreatedDate;
            if(IterWhattId != null){
                iterActivity.WhatId__c = IterWhattId;
                ObjectApiName = IterWhattId.getSObjectType().getDescribe().getName();
                iterActivity.WhatId_ObjectApi_Name__c = ObjectApiName;
            }
            if( (oldMap.containsKey(iterActivity.Id)) && (oldMap.get(iterActivity.Id).Status__c == 'Delivered') ){ 
                iterActivity.Status__c = 'Delivered';
            }
        }
    }

    public static void handleAfterUpdate() {

    }

    public static void handleBeforeDelete() {
        // for(Activity__c iterActivity : ((List<Activity__c>)Trigger.old)){
        //     String ExternalContactPoint = String.isNotBlank(iterActivity.Formatted_Phone__c) ? iterActivity.Formatted_Phone__c : iterActivity.Email__c;
        // }
        
    }

    public static void handleAfterDelete() {
        
    }

    public static void handleAfterUnDelete() {
       
    }
    
}