force-app/main/default/objects/Account/fields/Formatted_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Formatted_Phone_Number__c</fullName>
    <label>Formatted Phone Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Last_Created_Verification_Pin__c.field-meta.xml
<CustomField>
    <fullName>Last_Created_Verification_Pin__c</fullName>
    <label>Last Created Verification Pin</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Last_Created_Verification_Pin_Time__c.field-meta.xml
<CustomField>
    <fullName>Last_Created_Verification_Pin_Time__c</fullName>
    <label>Last Created Verification Pin Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Member_Stage</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Formatted_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Formatted_Phone_Number__c</fullName>
    <label>Formatted Phone Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Phone_Verified__c.field-meta.xml
<CustomField>
    <fullName>Phone_Verified__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Phone Verified</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lead</fullName>
            </value>
            <value>
                <fullName>Verified</fullName>
            </value>
            <value>
                <fullName>Appointment Scheduled</fullName>
            </value>
            <value>
                <fullName>Appointment No Show</fullName>
            </value>
            <value>
                <fullName>Appointment Completed</fullName>
            </value>
            <value>
                <fullName>Active Customer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <externalId>true</externalId>
    <label>UUID</label>
    <length>250</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Member.recordType-meta.xml
<RecordType>
    <fullName>Member</fullName>
    <active>true</active>
    <label>Member</label>
</RecordType>

force-app/main/default/globalValueSets/Member_Stage.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Lead</fullName>
        <default>true</default>
        <label>Lead</label>
    </customValue>
    <customValue>
        <fullName>Verified</fullName>
    </customValue>
    <customValue>
        <fullName>Appointment Scheduled</fullName>
    </customValue>
    <customValue>
        <fullName>Appointment No Show</fullName>
    </customValue>
    <customValue>
        <fullName>Appointment Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Active Customer</fullName>
    </customValue>
    <description>Used to track new member qualifying progress</description>
    <masterLabel>Member Stage</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/MemberService.cls
public without sharing class MemberService {
    public MemberService() {

    }

    public class Member {
        public String Name { get; set; }
        public String Id { get; set; }
        public String FirstName { get; set; }
        public String LastName { get; set; }
        public String PhoneNumber { get; set; }
        public String PhoneNumberFormatted { get; set; }
        public String Stage { get; set; }
        public Date dob { get; set; }
        public String uuid { get; set; }
        public String lastVarificationPin { get; set; }
        public DateTime lastVarificationPinTime { get; set; }
        public Boolean isphoneverified { get; set; }
        public sObject memberRecord { get; set; }
    }

    public static Member getMemberInformation(String salesforceRecordUUID, String phonenumber, String firstname, String lastname, String dateofbirthString) {
        Member memberinfo = new Member();
        try {
            List<sObject> records = findMember( salesforceRecordUUID,  phonenumber,  firstname,  lastname,  dateofbirthString);
            if (records.size() > 0) {
                memberinfo = fillMemberInfo(records[0]);
            }
        } catch (Exception e) {
            throw new MemberServiceException(e.getMessage()+'\n'+e.getStackTraceString());
        }
        return memberinfo;

    }

    public static Member fillMemberInfo(sObject record) {
        String firstname = '', lastname = '';
        Member memberinfo = new Member();
        memberinfo.memberRecord = record;
        try {
            if (record instanceOf Account) {
                firstname = (String)record.get('First_Name__c');
                lastname = (String)record.get('Last_Name__c');
                memberinfo.Id = (String)record.get('Id');
                memberinfo.uuid = (String)record.get('UUID__c');
                memberinfo.FirstName = (String.isNotBlank(firstname)) ? firstname : '';
                memberinfo.LastName = (String.isNotBlank(lastname)) ? lastname : '';
                memberinfo.Name = (String)record.get('Name');
                memberinfo.PhoneNumberFormatted = (String)record.get('Formatted_Phone_Number__c');
                memberinfo.Stage = (String)record.get('Stage__c');
                
                memberinfo.lastVarificationPin = (String)record.get('Last_Created_Verification_Pin__c');
                memberinfo.lastVarificationPinTime = (DateTime)record.get('Last_Created_Verification_Pin_Time__c');
                memberinfo.isphoneverified = (Boolean)record.get('Phone_Verified__c');
            } 
            else if (record instanceOf Contact) {
                firstname = (String)record.get('FirstName');
                lastname = (String)record.get('LastName');
                memberinfo.Id = (String)record.get('Id');
                memberinfo.uuid = (String)record.get('UUID__c');
                memberinfo.FirstName = (String.isNotBlank(firstname)) ? firstname : '';
                memberinfo.LastName = (String.isNotBlank(lastname)) ? lastname : '';
                memberinfo.Name = (String.isNotBlank(firstname) ? firstname : '') + '' + (String.isNotBlank(firstname) ? ' ' : '') + '' + (String.isNotBlank(lastname) ? lastname : '');
                memberinfo.PhoneNumberFormatted = (String)record.get('Formatted_Phone_Number__c');
                memberinfo.Stage = (String)record.get('Stage__c');
                
                memberinfo.lastVarificationPin = (String)record.get('Last_Created_Verification_Pin__c');
                memberinfo.lastVarificationPinTime = (DateTime)record.get('Last_Created_Verification_Pin_Time__c');
                memberinfo.isphoneverified = (Boolean)record.get('Phone_Verified__c');
            }
            else {
                throw new MemberServiceException('Invalid sObject retrived.');
            }
        } catch (Exception e) {
            throw new MemberServiceException(e.getMessage()+'\n'+e.getStackTraceString());
        }
        return memberinfo;
    }

    /**
     * @brief replaces the find account method in DialogFlow_Helper to dynamically search based on Account Share Model.
     * TODO - Impletent Agent based member search, 
     */
    public static List<sObject> findMember(String salesforceRecordUUID, String phonenumber, String firstname, String lastname, String dateofbirthString) {
        String accountId = SYS_DataCacheFactory.accountId;
        List<sObject> results = new List<sObject>();

        if (accountId != NULL) {
            List<Contact> findContact  = new List<Contact>();
            String objectapiname = 'Contact';
            
            if( String.isNotBlank(salesforceRecordUUID) ) {
                if ((salesforceRecordUUID.length() == 15) || (salesforceRecordUUID.length() == 18)) {
                    objectapiname = Id.valueOf(salesforceRecordUUID).getSObjectType().getDescribe().getName();
                }
            }
    
            String accountFilterCriteria = ' WHERE isDeleted = false';
            if( String.isNotBlank(salesforceRecordUUID) ) {
                if ((salesforceRecordUUID.length() == 15) || (salesforceRecordUUID.length() == 18)) {
                    accountFilterCriteria += ' AND Id =: salesforceRecordUUID';
                } else {
                    accountFilterCriteria += ' AND UUID__c =: salesforceRecordUUID';
                }
            } else {
                if( String.isNotBlank(phonenumber) ) {
                    phonenumber = phonenumber.replaceAll('[^\\+\\d]','');
                    accountFilterCriteria += ' AND Formatted_Phone_Number__c =: phonenumber';
                }
                if( String.isNotBlank(firstname) ) {
                    accountFilterCriteria += ' AND firstname =: firstname';
                }
                if( String.isNotBlank(lastname) ) {
                    accountFilterCriteria += ' AND lastname =: lastname';
                }
                if( String.isNotBlank(dateofbirthString) ) {
                    Date DateOfBirth = Date.valueOf(dateofbirthString);
                    accountFilterCriteria += ' AND Birthdate =: DateOfBirth';
                }
            }
            
            String findContactQuery = 'SELECT ' + SYS_Helper.getAllFieldsFor(objectapiname) +
            ' FROM '+objectapiname + accountFilterCriteria + ' ORDER BY CreatedDate DESC';
            System.debug('accountFilterCriteria '+ accountFilterCriteria);
            findContact = Database.query(findContactQuery);

            results = findContact;
        }
        else {
            List<Account> findAccount  = new List<Account>();
            String objectapiname = 'Account';
            
            if( String.isNotBlank(salesforceRecordUUID) ) {
                if ((salesforceRecordUUID.length() == 15) || (salesforceRecordUUID.length() == 18)) {
                    objectapiname = Id.valueOf(salesforceRecordUUID).getSObjectType().getDescribe().getName();
                }
            }
    
            String accountFilterCriteria = ' WHERE isDeleted = false';
            if( String.isNotBlank(salesforceRecordUUID) ) {
                if ((salesforceRecordUUID.length() == 15) || (salesforceRecordUUID.length() == 18)) {
                    accountFilterCriteria += ' AND Id =: salesforceRecordUUID';
                } else {
                    accountFilterCriteria += ' AND UUID__c =: salesforceRecordUUID';
                }
            } else {
                if( String.isNotBlank(phonenumber) ) {
                    phonenumber = phonenumber.replaceAll('[^\\+\\d]','');
                    accountFilterCriteria += ' AND Formatted_Phone_Number__c =: phonenumber';
                }
                if( String.isNotBlank(firstname) ) {
                    accountFilterCriteria += ' AND First_Name__c =: firstname';
                }
                if( String.isNotBlank(lastname) ) {
                    accountFilterCriteria += ' AND Last_Name__c =: lastname';
                }
                if( String.isNotBlank(dateofbirthString) ) {
                    Date DateOfBirth = Date.valueOf(dateofbirthString);
                    accountFilterCriteria += ' AND Date_of_Birth__c =: DateOfBirth';
                }
            }
            
            String findAccountQuery = 'SELECT ' + SYS_Helper.getAllFieldsFor('Account') +
            ' FROM Account' + accountFilterCriteria + ' ORDER BY CreatedDate DESC';
            findAccount = Database.query(findAccountQuery);

            results = findAccount;

        }
        return results;
    }

    public class MemberServiceException extends Exception { }
}