force-app/main/default/objects/Account/fields/Formatted_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Formatted_Phone_Number__c</fullName>
    <label>Formatted Phone Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Plivo_Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Plivo_Country_Code__c</fullName>
    <inlineHelpText>Entered Country Code utilized in all PMA Contacts</inlineHelpText>
    <label>Plivo Country Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Plivo_PHLO_Id__c.field-meta.xml
<CustomField>
    <fullName>Plivo_PHLO_Id__c</fullName>
    <label>Plivo PHLO Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Plivo_Sender_Id__c.field-meta.xml
<CustomField>
    <fullName>Plivo_Sender_Id__c</fullName>
    <inlineHelpText>Plivo Phone Number, shortcode, or Alphanumeric Sender ID.</inlineHelpText>
    <label>Plivo Sender Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Default_Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Default_Payment_Method__c</fullName>
    <inlineHelpText>Default Card or Bank Token</inlineHelpText>
    <label>Default Payment Method</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Formatted_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Formatted_Phone_Number__c</fullName>
    <label>Formatted Phone Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Member_Type__c.field-meta.xml
<CustomField>
    <fullName>Member_Type__c</fullName>
    <defaultValue>&apos;Subscriber&apos;</defaultValue>
    <description>Guest Member was a one-time Member without monthly membership fees they can create order for one time later they have to pay membership fees</description>
    <inlineHelpText>Guest Member was a one-time Member without monthly membership fees</inlineHelpText>
    <label>Member Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Guest</fullName>
            </value>
            <value>
                <fullName>Subscriber</fullName>
                <default>true</default>
                <label>Subscriber</label>
            </value>
            <value>
                <fullName>Anonymous</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Membership_Type__c.field-meta.xml
<CustomField>
    <fullName>Membership_Type__c</fullName>
    <label>Membership Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Member_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Individual</fullName>
            </value>
            <value>
                <fullName>Family</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/StripeCustomerId__c.field-meta.xml
<CustomField>
    <fullName>StripeCustomerId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>StripeCustomerId</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <externalId>true</externalId>
    <label>UUID</label>
    <length>250</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/PaymentMethodsController.cls
public without sharing class PaymentMethodsController {
    private static StripeService stripeService = new StripeService();
    private static StripeRestService stripeRest = new StripeRestService();
    private static CustomLabelsService customLabelsService = new CustomLabelsService();
	private static TransactionService txnService = new TransactionService();
    
    public List<Stripe.Card> cards { get; set; }
    public Stripe.Card newCard { get; set; }

    public String contactUUID { get; set; }
    public String stripeCustomerId { get; set; }
    public String defaultPaymentMethodId { get; set; }
    public String newPaymentMethodId { get; set; }
    public String organization { get; set; }
    public String stripePaymentRequestJson { get; set; }
    public String error { get; set; }
    public String stripeError { get; set; }
    public static String stripePublishableKey { get; set; }
    public static String stripeAccessToken { get; set; }
    public Boolean appMode { get; set; }
    public static PMA_SearchController.StripeApiTokensWrap apiKeyWrap { get; set; }
    public String labelsJson { get; set; }
    public Map<String, Object> labels { get; set; }

    public Contact contact { get; set; }

    public PaymentMethodsController() {
        contactUUID = ApexPages.currentPage().getParameters().get('reqid');
        contact = [SELECT Id, Name, LastName, FirstName, Member_Type__c, Phone_Number__c, Formatted_Phone_Number__c,
            Membership_Type__c, Gender__c, StripeCustomerId__c, Default_Payment_Method__c, UUID__c,
            AccountId, Account.Name, Account.OwnerId, Account.Plivo_Country_Code__c,
            Account.Plivo_Sender_Id__c, Account.Plivo_PHLO_Id__c FROM Contact WHERE UUID__c =: contactUUID
        ];
        assert(!(contact == null), 'No Payment Methods found');

        initStripeProps();

        //Custom Labels Collection
        labels = customLabelsService.getCustomLabels();
        labelsJson = JSON.serialize(labels);

    }
    public void assert(Boolean condition, String message) {
        if (!condition) {
            this.error = message;
        }
    }

    public void resetStripeError(){
        stripeError = null;
    }

    public void refreshStripeError(){
        stripeError = this.stripeError;
    }

    public void initStripeProps() {
        stripeError = null;
        try {
            if ((contact != null) && (contact.AccountId != null)) {
                apiKeyWrap = PMA_SearchController.fetchStripeApiToken(contact.AccountId);
                organization = apiKeyWrap.Name;
                stripePublishableKey = apiKeyWrap.PublicKey;
                stripeAccessToken = apiKeyWrap.accessToken;
                appMode = apiKeyWrap.testMode;
                defaultPaymentMethodId = contact.Default_Payment_Method__c;
                if (String.isBlank(stripeAccessToken)) {
                    assert(false, System.Label.error_message_stripe_setup_error);
                }
                assert(organization != null, System.Label.error_message_invalid_organization);
                assert(stripePublishableKey != null, System.Label.error_message_stripe_setup_error);

                cards = stripeRest.getCards(contact.StripeCustomerId__c);

            }
        } catch (Stripe.RestException ex) {
            Stripe.ErrorResponse CardError;
            CardError = ex.errorResponse;
            stripeError = CardError.error.message;
            System.debug('stripeError ex ' + ex);
            System.debug('stripeError ' + stripeError);
        } catch (JSONException ex) {
            error = System.Label.error_message_bad_request;
        }
        error = null;
    }

    public void saveNewCard() {
        error = null;
        stripeError = null;        
        try {
            initStripeProps();
            Stripe.UserPaymentRequest stripePaymentRequest = new Stripe.UserPaymentRequest();
            stripePaymentRequest = (Stripe.UserPaymentRequest) JSON.deserialize(stripePaymentRequestJson, Stripe.UserPaymentRequest.class);
            stripeCustomerId = contact.StripeCustomerId__c;
            String stripeToken = stripePaymentRequest.stripeToken == null ? stripePaymentRequest.bankToken : stripePaymentRequest.stripeToken;

            Map < String, Object > metadata = new Map < String, Object > ();
            metadata.put('contactId', contact.Id);
            metadata.put('accountId', contact.AccountId);
            System.debug('stripeAccessToken=' + stripeAccessToken);
            newCard = stripeRest.createCard(stripeCustomerId, stripeToken, metadata, stripeAccessToken);
            System.debug('Created new card for customer=' + stripeCustomerId + ' with stripe card id=' +
            newCard.id);
            newPaymentMethodId = newCard.id;
            stripeRest.setDefaultPaymentSource(stripeCustomerId, newPaymentMethodId, stripeAccessToken);

        } catch (Stripe.RestException ex) {
            Stripe.ErrorResponse CardError;
            CardError = ex.errorResponse;
            stripeError = CardError.error.message;
            System.debug('stripeError ex ' + ex);
            System.debug('stripeError ' + stripeError);
        } catch (JSONException ex) {
            error = System.Label.error_message_bad_request;
        }
        error = null;
    }

}