force-app/main/default/objects/Account/fields/Plivo_Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Plivo_Country_Code__c</fullName>
    <inlineHelpText>Entered Country Code utilized in all PMA Contacts</inlineHelpText>
    <label>Plivo Country Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Plivo_PHLO_Id__c.field-meta.xml
<CustomField>
    <fullName>Plivo_PHLO_Id__c</fullName>
    <label>Plivo PHLO Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Plivo_Sender_Id__c.field-meta.xml
<CustomField>
    <fullName>Plivo_Sender_Id__c</fullName>
    <inlineHelpText>Plivo Phone Number, shortcode, or Alphanumeric Sender ID.</inlineHelpText>
    <label>Plivo Sender Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Activity__c/Activity__c.object-meta.xml
<CustomObject>
    <label>PMA Activity</label>
    <nameField>
        <displayFormat>Activity-{0}</displayFormat>
        <label>Activity#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PMA Activities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Activity__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>PMA_Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activity__c/fields/ActionId__c.field-meta.xml
<CustomField>
    <fullName>ActionId__c</fullName>
    <label>ActionId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Activity__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>PMA Activities</relationshipLabel>
    <relationshipName>PMA_Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activity__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Activity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activity__c/fields/Direction__c.field-meta.xml
<CustomField>
    <fullName>Direction__c</fullName>
    <label>Direction</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>OUTBOUND</fullName>
            </value>
            <value>
                <fullName>INBOUND</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Activity__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Queued</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Undelivered</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Skipped</fullName>
            </value>
            <value>
                <fullName>Replied</fullName>
            </value>
            <value>
                <fullName>ringing</fullName>
                <label>Ringing</label>
            </value>
            <value>
                <fullName>hangup</fullName>
                <label>Hangup</label>
            </value>
            <value>
                <fullName>connected</fullName>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>answer</fullName>
                <label>Answered</label>
            </value>
            <value>
                <fullName>Sending</fullName>
            </value>
            <value>
                <fullName>no-answer</fullName>
                <label>Not Answered</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Activity__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>sms</fullName>
            </value>
            <value>
                <fullName>mms</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Call</fullName>
            </value>
            <value>
                <fullName>Recording</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Member_Type__c.field-meta.xml
<CustomField>
    <fullName>Member_Type__c</fullName>
    <defaultValue>&apos;Subscriber&apos;</defaultValue>
    <description>Guest Member was a one-time Member without monthly membership fees they can create order for one time later they have to pay membership fees</description>
    <inlineHelpText>Guest Member was a one-time Member without monthly membership fees</inlineHelpText>
    <label>Member Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Guest</fullName>
            </value>
            <value>
                <fullName>Subscriber</fullName>
                <default>true</default>
                <label>Subscriber</label>
            </value>
            <value>
                <fullName>Anonymous</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Membership_Type__c.field-meta.xml
<CustomField>
    <fullName>Membership_Type__c</fullName>
    <label>Membership Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Member_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Individual</fullName>
            </value>
            <value>
                <fullName>Family</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Payment_SMS_Sent__c.field-meta.xml
<CustomField>
    <fullName>Payment_SMS_Sent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Payment SMS Sent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/StripeCustomerId__c.field-meta.xml
<CustomField>
    <fullName>StripeCustomerId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>StripeCustomerId</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <externalId>true</externalId>
    <label>UUID</label>
    <length>250</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Member.recordType-meta.xml
<RecordType>
    <fullName>Member</fullName>
    <active>true</active>
    <label>Member</label>
</RecordType>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>PMA Order</label>
    <nameField>
        <displayFormat>O-{00000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PMA Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Order_Type__c.field-meta.xml
<CustomField>
    <fullName>Order_Type__c</fullName>
    <label>Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Registration</fullName>
            </value>
            <value>
                <fullName>POS</fullName>
            </value>
            <value>
                <fullName>Subscription</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Draft&quot;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Item_Status__c.field-meta.xml
<CustomField>
    <fullName>Item_Status__c</fullName>
    <label>Item Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/List_Price__c.field-meta.xml
<CustomField>
    <fullName>List_Price__c</fullName>
    <formula>Product_Option__r.Option_Total_Price__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>List Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <formula>Product_Option__r.Name</formula>
    <label>Product Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Product_Option__c.field-meta.xml
<CustomField>
    <fullName>Product_Option__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Option</label>
    <referenceTo>Product_Option__c</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/Payment_Method__c.object-meta.xml
<CustomObject>
    <label>Payment Method</label>
    <nameField>
        <label>Holder&apos;s Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <externalId>true</externalId>
    <label>UUID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product_Option__c/Product_Option__c.object-meta.xml
<CustomObject>
    <label>Product Option</label>
    <nameField>
        <label>Option Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Option</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Option__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Product Option</relationshipLabel>
    <relationshipName>Product_Option</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product_Option_Component__c/Product_Option_Component__c.object-meta.xml
<CustomObject>
    <label>Product Option Component</label>
    <nameField>
        <label>Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Option Component</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Option_Component__c/fields/Product_Option__c.field-meta.xml
<CustomField>
    <fullName>Product_Option__c</fullName>
    <label>Product Option</label>
    <referenceTo>Product_Option__c</referenceTo>
    <relationshipLabel>Product Option Component</relationshipLabel>
    <relationshipName>Product_Option_Component</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product_Option_Component__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <inlineHelpText>Product Price Type - Onetime or Subscription</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>one_time</fullName>
                <label>One Time</label>
            </value>
            <value>
                <fullName>recurring</fullName>
                <label>Subscription</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/ContactId__c.field-meta.xml
<CustomField>
    <fullName>ContactId__c</fullName>
    <label>ContactId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PMA_SearchControllerTest.cls
@isTest
public class PMA_SearchControllerTest {
	@TestSetup
    static void PMA_SearchControllerTest(){
        PMA_TestDataFactory.createTestAccountWithContactsRecords(1, 3);  
    }
    
    @IsTest
    static void testgetOpenTabMembers(){
		Account getcurrAccount = PMA_TestDataFactory.getTestAccountWithContactsRecords();
        List<Contact> fetchContact = getcurrAccount.Contacts;
        System.debug('fetchContact test ' + fetchContact);
        for(Contact con : fetchContact){
        	PMA_TestDataFactory.createTestOrderRecords(getcurrAccount.Id, con.Id,'Draft');
        }
        Order__c fetchOrder = PMA_TestDataFactory.getTestOrderwithOrderItemRecords();
        
        List<PMA_SearchController.membersOrdersWrapper>  listOpenTabMembers = PMA_SearchController.getOpenTabMembers();
        List<Order__c> getOrderList = [SELECT Id,(SELECT Id,Name,Order__c,Product__c,Product__r.Name,Quantity__c,List_Price__c,Line_Total_Price__c,Total_Price__c,CreatedDate,LastModifiedDate FROM Order_Items__r),Name,Order_Type__c,Member__c,Member__r.Name,Member__r.Active__c,Vendor__c,Vendor__r.Name,Account__c,Account__r.Name,Status__c,Total_Price__c,UUID__c,CreatedDate,LastModifiedDate,OwnerId FROM Order__c];
        if(listOpenTabMembers.size()>0){
            System.assert(getOrderList.size()>0);
        }
    }
    
    @IsTest
    static void testsearchMembers(){
    	List<PMA_SearchController.membersOrdersWrapper> memberWrapList = PMA_SearchController.searchActiveMembers('Test Contact');
        if(memberWrapList.size()>0){
            System.assert(memberWrapList.size()>0);
        }
	}
    
    @IsTest
    static void testfetchCurrentUserWrapper(){
        PMA_SearchController.CurrentUserWrap cuserWrap = PMA_SearchController.fetchCurrentUserWrapper();
        System.assertNotEquals(null, cuserWrap.contactRecord);
	}

    @IsTest
    static void testfetchActionRecordRelatedActivities(){
        Id MemberRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Member').getRecordTypeId();
        List<SYS_Integration_Metadata__c> accIntMetadata = new List<SYS_Integration_Metadata__c>();

        Account acc = new Account(Name = 'PMA Test Account', Plivo_Country_Code__c = '1',
            Plivo_Sender_Id__c = '12222222222', Plivo_PHLO_Id__c = 'Test123');
        insert acc;

        accIntMetadata.add(new SYS_Integration_Metadata__c(Account__c = acc.Id,
            Integration_Type__c = 'Plivo',
            Key__c = 'int-set',
            Value__c = 'Plivo'));
        accIntMetadata.add(new SYS_Integration_Metadata__c(Account__c = acc.Id,
            Integration_Type__c = 'Stripe',
            Key__c = 'int-set',
            Value__c = 'Stripe'));
        
        insert accIntMetadata;    

        SYS_OAuthConfig__c  oauthRecord = PMA_TestDataFactory.createTestSysOauthWithAccessToken(acc.Id);

        Contact cont = new Contact(FirstName = 'PMA',
            LastName = 'Test Contact',
            Member_Type__c = 'Subscriber',
            Membership_Type__c = 'Individual',
            Phone_Number__c = '999999999',
            StripeCustomerId__c = 'test_customer',
            Active__c = true,
            Payment_SMS_Sent__c = true,
            Payment_Date_Time__c = System.now(),
            Registration_Order_Created__c = true,
            RecordTypeId = MemberRecordTypeId,
            AccountId = acc.Id);
        insert cont;

        Payment_Method__c paymentmethodRecord = new Payment_Method__c(Account__c = acc.Id,Contact__c = cont.Id );
        insert paymentmethodRecord;

        Activity__c smsActivity = new Activity__c(
                Customer__c = cont.Id,
                Account__c = acc.Id,
                Direction__c = 'OUTBOUND',
                Type__c = 'sms',
                Email__c = 'dev@adisols.com',
                Status__c = 'Queued',
                When__c = System.now(),
                Phone__c = '9999999990',
                Subject__c = 'Test Activity',
                Message__c = 'Test Sms Content',
                ActionId__c = cont.Id
        );
        Insert smsActivity;
        List < Activity__c > allrelatedActivitiesList = PMA_SearchController.fetchActionRecordRelatedActivities(cont.Id);
        System.assertNotEquals(0, allrelatedActivitiesList.size());
	}

    @IsTest
    static void testsearchExcludeActiveMembers(){
        Account getcurrAccount = PMA_TestDataFactory.getTestAccountWithContactsRecords();
        List<Contact> fetchContact = getcurrAccount.Contacts;
        System.debug('fetchContact test ' + fetchContact);
        for(Contact con : fetchContact){
        	PMA_TestDataFactory.createTestOrderRecords(getcurrAccount.Id, con.Id, 'Draft');
        }
    	List<PMA_SearchController.membersOrdersWrapper> memberWrapList = PMA_SearchController.searchActiveMembers('Test Contact');
        if(memberWrapList.size()>0){
            System.assert(memberWrapList.size()>0);
        }
	}
     
    @IsTest
    static void testgetOrderDetailsByIdOrUUID(){
        // Order__c getOrderDetailsByIdOrUUID( String orderIdOrUUID )
        Account getcurrAccount = PMA_TestDataFactory.getTestAccountWithContactsRecords();
        List<Contact> fetchContact = getcurrAccount.Contacts;
        System.debug('fetchContact test ' + fetchContact);
        Integer i = 0;
        for(Contact con : fetchContact){
            if(i == 0){
        		PMA_TestDataFactory.createTestOrderRecords(getcurrAccount.Id, con.Id,'Draft');
            }
			i++;
        }
        Order__c fetchOrder = PMA_TestDataFactory.getTestOrderwithOrderItemRecords();
        Order__c fetchOrderbyUUID = PMA_SearchController.getOrderDetailsByIdOrUUID( fetchOrder.UUID__c );
        system.assertEquals(fetchOrder.Total_Price__c, fetchOrderbyUUID.Total_Price__c);
    }
     
    @IsTest
    static void testcreateDraftOrderRecord(){
        Id vendorRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Member').getRecordTypeId();
        Contact newContact = new Contact();
        newContact.FirstName = 'Member';
        newContact.LastName = 'Contact';
        newContact.RecordTypeId = vendorRecordTypeId;
        insert newContact;
        Account getcurrAccount = PMA_TestDataFactory.getTestAccountWithContactsRecords();
        List<Contact> fetchContact = getcurrAccount.Contacts;
        User userRecord = PMA_SearchController.fetchCurrentUser();
        userRecord.ContactId__c = newContact.Id;
        update userRecord;
        for(Contact con : fetchContact){
            Order__c orderRecord = PMA_SearchController.createDraftOrderRecord( con.Id );
        }
        Order__c fetchOrder = PMA_TestDataFactory.getTestOrderwithOrderItemRecords();
        system.assertEquals('Draft', fetchOrder.Status__c);
    }
    
    @IsTest
    static void testfetchCurrentUser(){
        User userRecord = PMA_SearchController.fetchCurrentUser();
        system.assertNotEquals(null, userRecord.Name);
    }
    
    @IsTest
    static void testgetOrderItemsForFulfillment(){
        List<Order_Item__c> orderfullfillRecords = PMA_SearchController.getOrderItemsForFulfillment();
        if(orderfullfillRecords.size()>0){
            System.assert(orderfullfillRecords.size()>0);
        }
    }
    
    @IsTest
    static void testgetKanbanWrapperDetails_Apex(){
        List<String> fieldsList =  new List<String>{'Name', 'Product__c','Product_Name__c' , 'Product__r.Name', 'Quantity__c', 'Notes__c', 'Item_Status__c', 'Order__c' , 'Order__r.Order_Type__c','Order__r.Status__c'};
        PMA_SearchController.kanbanWrap kanbanWrapvar = PMA_SearchController.getKanbanWrapperDetails_Apex('Order_Item__c',fieldsList ,'Item_Status__c');
        if(kanbanWrapvar.pickVals.size()>0){
            System.assert(kanbanWrapvar.pickVals.size()>0);
        }
    }
    
    @IsTest
    static void testgetUpdatePickListValue_Apex(){
		Account getcurrAccount = PMA_TestDataFactory.getTestAccountWithContactsRecords();
        List<Contact> fetchContact = getcurrAccount.Contacts;
        System.debug('fetchContact test ' + fetchContact);
        for(Contact con : fetchContact){
        	PMA_TestDataFactory.createTestOrderRecords(getcurrAccount.Id, con.Id,'Draft');
        }
        Order__c fetchOrder = PMA_TestDataFactory.getTestOrderwithOrderItemRecords();
        Product__c createprod = PMA_TestDataFactory.createProduct('Cheese Burger' , getcurrAccount.Id , false);
        insert createprod;
        Product_Option__c createprodOption = PMA_TestDataFactory.createProductOption('Cheese Burger' , createprod.Id , true); 
        Product_Option_Component__c createOptionComponent = PMA_TestDataFactory.createOptionComponent('Cheese Burger' , createprodOption.Id, '' , true); 
        
        PMA_TestDataFactory.createTestOrderItemRecords(3, fetchOrder.Id , createprodOption.Id);
        Order_Item__c latestOrderItem = [SELECT Id,Name,Item_Status__c FROM Order_Item__c LIMIT 1];
        if(latestOrderItem!= null){
            String updateStatus = PMA_SearchController.getUpdatePickListValue_Apex(latestOrderItem.Id, 'Item_Status__c' , 'Completed');
            system.assertEquals('Success', updateStatus);
        }
    }  
    
}