force-app/main/default/objects/Account/fields/Plivo_PHLO_Id__c.field-meta.xml
<CustomField>
    <fullName>Plivo_PHLO_Id__c</fullName>
    <label>Plivo PHLO Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Member_Type__c.field-meta.xml
<CustomField>
    <fullName>Member_Type__c</fullName>
    <defaultValue>&apos;Subscriber&apos;</defaultValue>
    <description>Guest Member was a one-time Member without monthly membership fees they can create order for one time later they have to pay membership fees</description>
    <inlineHelpText>Guest Member was a one-time Member without monthly membership fees</inlineHelpText>
    <label>Member Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Guest</fullName>
            </value>
            <value>
                <fullName>Subscriber</fullName>
                <default>true</default>
                <label>Subscriber</label>
            </value>
            <value>
                <fullName>Anonymous</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Membership_Type__c.field-meta.xml
<CustomField>
    <fullName>Membership_Type__c</fullName>
    <label>Membership Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Member_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Individual</fullName>
            </value>
            <value>
                <fullName>Family</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Payment_SMS_Sent__c.field-meta.xml
<CustomField>
    <fullName>Payment_SMS_Sent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Payment SMS Sent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/StripeCustomerId__c.field-meta.xml
<CustomField>
    <fullName>StripeCustomerId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>StripeCustomerId</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <externalId>true</externalId>
    <label>UUID</label>
    <length>250</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Member.recordType-meta.xml
<RecordType>
    <fullName>Member</fullName>
    <active>true</active>
    <label>Member</label>
</RecordType>

force-app/main/default/objects/Google_Calendar__c/Google_Calendar__c.object-meta.xml
<CustomObject>
    <label>Google Calendar</label>
    <nameField>
        <displayFormat>GC-{000000}</displayFormat>
        <label>Google Calendar No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Google Calendar</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Google_Calendar__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Google_Calendars</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Google_Calendar__c/fields/Calendar_Name__c.field-meta.xml
<CustomField>
    <fullName>Calendar_Name__c</fullName>
    <label>Calendar Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Google_Calendar__c/fields/Calendar_Type__c.field-meta.xml
<CustomField>
    <fullName>Calendar_Type__c</fullName>
    <inlineHelpText>Shift Calendar - for Shifts of resource
Booking Calendar - for Booking Appointments</inlineHelpText>
    <label>Calendar Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Shift Calendar</fullName>
            </value>
            <value>
                <fullName>Booking Calendar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Google_Calendar__c/fields/Google_Calendar_Id__c.field-meta.xml
<CustomField>
    <fullName>Google_Calendar_Id__c</fullName>
    <externalId>true</externalId>
    <label>Google Calendar Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Google_Calendar__c/fields/PMA_Product__c.field-meta.xml
<CustomField>
    <fullName>PMA_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PMA Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipName>Google_Calendars</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Google_Calendar__c/fields/TimeZone__c.field-meta.xml
<CustomField>
    <fullName>TimeZone__c</fullName>
    <label>TimeZone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>America/Asuncion</fullName>
            </value>
            <value>
                <fullName>Asia/Kolkata</fullName>
            </value>
            <value>
                <fullName>America/Los_Angeles</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Allow_scheduling__c.field-meta.xml
<CustomField>
    <fullName>Allow_scheduling__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Allow Scheduling</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Google_Booking_Calendar_Id__c.field-meta.xml
<CustomField>
    <fullName>Google_Booking_Calendar_Id__c</fullName>
    <inlineHelpText>Google Booking Calendar External Id</inlineHelpText>
    <label>Google Booking Calendar Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Google_Shift_Calendar_Id__c.field-meta.xml
<CustomField>
    <fullName>Google_Shift_Calendar_Id__c</fullName>
    <inlineHelpText>Google Shift Calendar External Id</inlineHelpText>
    <label>Google Shift Calendar Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Meet_Duration__c.field-meta.xml
<CustomField>
    <fullName>Meet_Duration__c</fullName>
    <label>Meet Duration</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>30</fullName>
                <label>30 Minutes</label>
            </value>
            <value>
                <fullName>45</fullName>
                <label>45 Minutes</label>
            </value>
            <value>
                <fullName>60</fullName>
                <label>60 Minutes</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Minimum_Lead_Time__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Lead_Time__c</fullName>
    <label>Minimum Lead Time</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>30</fullName>
                <label>30 Minutes</label>
            </value>
            <value>
                <fullName>45</fullName>
                <label>45 Minutes</label>
            </value>
            <value>
                <fullName>60</fullName>
                <label>60 Minutes</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>15 Minutes</label>
            </value>
            <value>
                <fullName>0</fullName>
                <label>0 Minutes</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product_Family__c.field-meta.xml
<CustomField>
    <fullName>Product_Family__c</fullName>
    <inlineHelpText>POS - For POS Product || Scheduling - For Scheduling Product || Assets - For Inventory Product</inlineHelpText>
    <label>Product Family</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Membership Fees</fullName>
            </value>
            <value>
                <fullName>POS</fullName>
                <default>true</default>
                <label>POS</label>
            </value>
            <value>
                <fullName>Scheduling</fullName>
            </value>
            <value>
                <fullName>Assets</fullName>
            </value>
            <value>
                <fullName>Global</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/TimeZone__c.field-meta.xml
<CustomField>
    <fullName>TimeZone__c</fullName>
    <label>TimeZone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>America/Asuncion</fullName>
            </value>
            <value>
                <fullName>Asia/Kolkata</fullName>
            </value>
            <value>
                <fullName>America/Los_Angeles</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <externalId>true</externalId>
    <label>UUID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/Scheduling_TestDataFactory.cls
@IsTest
public class Scheduling_TestDataFactory {
    // Account Contact Product google calender 2  
    public static void createTestAccountWithContactsRecords(Integer numAccts, Integer numContactsPerAcct){
        List<Account> accountsList = new List<Account>();
        Id MemberRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Member').getRecordTypeId();
        List<SYS_Integration_Metadata__c> accIntMetadata = new List<SYS_Integration_Metadata__c>();
        
        for(Integer i=0;i<numAccts;i++) {
            Account tempAcc = new Account();
            tempAcc.Name = 'Test Account' + i;
            tempAcc.UUID__c = SYS_Helper.getUUID();
            tempAcc.Email__c = 'testemail' + i+'@adisols.com';
            tempAcc.Plivo_PHLO_Id__c = 'Test123';
            accountsList.add(tempAcc);
        }
        insert accountsList;
        
        List<Contact> contactsList = new List<Contact>();

        for (Integer j=0;j<numAccts;j++) {
            Account acct = accountsList[j];  
            
            if( j==0 ){
                SYS_OAuthConfig__c oauthRecord = new SYS_OAuthConfig__c();
                oauthRecord.Name = 'TestAccount';
                oauthRecord.Account__c = acct.Id;
                oauthRecord.Client_Id__c = 'testPublicKey';
                oauthRecord.Access_Token__c = 'testAccessToken';
                oauthRecord.Test_Mode__c = true;
                oauthRecord.Grant_Type__c = 'authorization_code';
                oauthRecord.Integration_Type__c = 'Calendar';
                oauthRecord.Token_type__c = 'Bearer';
                oauthRecord.Config_ID__c = 'SYSOAUTH-' + Integer.valueof((Math.random() * 1000));
                insert oauthRecord;
            }

            // For each account just inserted, add contacts
            for (Integer k=numContactsPerAcct*j;k<numContactsPerAcct*(j+1);k++) {
                accIntMetadata.add(new SYS_Integration_Metadata__c(Account__c = acct.Id,
                                    Integration_Type__c = 'Plivo', 
                                    Key__c = 'int-set',
                                    Value__c = 'Plivo'));
                accIntMetadata.add(new SYS_Integration_Metadata__c(Account__c = acct.Id,
                                    Integration_Type__c = 'Stripe', 
                                    Key__c = 'int-set',
                                    Value__c = 'Stripe'));     
                accIntMetadata.add(new SYS_Integration_Metadata__c(Account__c = acct.Id,
                                    Integration_Type__c = 'Calendar', 
                                    Key__c = 'int-set',
                                    Value__c = 'Calendar'));                                                
                Contact tempCont = new Contact();
                tempCont.FirstName='Test'+k;
                tempCont.LastName='Contact'+k;
                tempCont.Email= 'testemail' + k +'@adisols.com';
                tempCont.AccountId=acct.Id;

                tempCont.Member_Type__c = 'Subscriber';
                tempCont.Membership_Type__c = 'Individual';
                tempCont.Phone_Number__c = '999999999' +k;
                tempCont.StripeCustomerId__c = 'test_customer'+k;
                tempCont.Active__c = true;
                tempCont.Payment_SMS_Sent__c = true;
                tempCont.Payment_Date_Time__c = System.now();
                tempCont.Registration_Order_Created__c = true;
                tempCont.RecordTypeId = MemberRecordTypeId;
                contactsList.add(tempCont);
            }
        }
        // Insert all Integration Metadata for all accounts
        insert accIntMetadata;
        // Insert all contacts for all accounts
        insert contactsList;
    }

    //Create Shift Calendar Record 
    public static Google_Calendar__c createTestShiftCalendarRecord(Id accountRecordId, String shiftCalendarExId, Boolean insertExternalId, Boolean doInsert){
        Integer IntrandomNumber = Integer.valueof((Math.random() * 1000));	//generates a random number from 0 to 1000
        //Shift Calendar
        Google_Calendar__c shiftGoogleCalTemp = new Google_Calendar__c();
        shiftGoogleCalTemp.Calendar_Name__c = 'S-Dr Smith ' + IntrandomNumber;
        shiftGoogleCalTemp.Calendar_Type__c = 'Shift Calendar';
        shiftGoogleCalTemp.TimeZone__c = 'America/Los_Angeles';
        if(insertExternalId){
            shiftGoogleCalTemp.Google_Calendar_Id__c = String.isNotBlank(shiftCalendarExId) ? shiftCalendarExId : ('exCalenderKeyShift' + IntrandomNumber);
        }
        
        shiftGoogleCalTemp.Account__c = accountRecordId;
        shiftGoogleCalTemp.Active__c = true;
        if(doInsert){
            insert shiftGoogleCalTemp;
        }
        return shiftGoogleCalTemp;
    }

    //Create Booking Calendar Record
    public static Google_Calendar__c createTestBookingCalendarRecord(Id accountRecordId, Id BookingProductId, String bookingCalendarExId, Boolean insertExternalId, Boolean doInsert){
        Integer IntrandomNumber = Integer.valueof((Math.random() * 1000));	//generates a random number from 0 to 1000
        //Booking Calendar
        Google_Calendar__c bookGoogleCalTemp = new Google_Calendar__c();
        bookGoogleCalTemp.Calendar_Name__c = 'B- ' + IntrandomNumber;
        bookGoogleCalTemp.Calendar_Type__c = 'Booking Calendar';
        bookGoogleCalTemp.TimeZone__c = 'America/Los_Angeles';
        if(insertExternalId){
            bookGoogleCalTemp.Google_Calendar_Id__c = String.isNotBlank(bookingCalendarExId) ? bookingCalendarExId : ('exCalenderKeyBooking' + IntrandomNumber);
        }
        bookGoogleCalTemp.Google_Calendar_Id__c = 'exCalenderKeyBooking' + IntrandomNumber;
        bookGoogleCalTemp.PMA_Product__c = BookingProductId;
        bookGoogleCalTemp.Account__c = accountRecordId;
        bookGoogleCalTemp.Active__c = true;
        if(doInsert){
            insert bookGoogleCalTemp;
        }
        return bookGoogleCalTemp;
    }

    public static Product__c createTestProductRecord(Id accountRecordId, String shiftCalendarExId, String bookingCalendarExId, Boolean insertExternalId, Boolean doInsert){
        Blob b = Crypto.GenerateAESKey(128);
        String h = EncodingUtil.ConvertTohex(b);
        String guid = h.SubString(0,8)+ '-' + h.SubString(8,12) + '-' + h.SubString(12,16) + '-' + h.SubString(16,20) + '-' + h.substring(20);
        Integer IntrandomNumber = Integer.valueof((Math.random() * 1000));	//generates a random number from 0 to 1000

        //Create one Scheduling Product
        Product__c BookingProduct = new Product__c();
        BookingProduct.Account__c = accountRecordId;
        BookingProduct.Name = 'Consultation';
        BookingProduct.Unit_Price__c = 12.5;
        BookingProduct.Active__c = true;
        BookingProduct.UUID__c = guid;
        BookingProduct.Allow_scheduling__c = true;
        BookingProduct.TimeZone__c = 'America/Los_Angeles';
        BookingProduct.Meet_Duration__c = '60';
        BookingProduct.Minimum_Lead_Time__c = '15';
        BookingProduct.Product_Family__c = 'Scheduling';
        if(insertExternalId){
            BookingProduct.Google_Shift_Calendar_Id__c = String.isNotBlank(shiftCalendarExId) ? shiftCalendarExId : ('exCalenderKeyBooking' + IntrandomNumber);
            BookingProduct.Google_Booking_Calendar_Id__c = String.isNotBlank(bookingCalendarExId) ? bookingCalendarExId : ('exCalenderKeyBooking' + IntrandomNumber);
        }
        if(doInsert){
            insert BookingProduct;
        }
        return BookingProduct;
    }

    public static Account getAccountDetails(){
        String AccountListQuery = 'SELECT ' + SYS_Helper.getAllFieldsFor('Account') +
                ' FROM Account LIMIT 1';
        List<Account> AccountList = Database.query(AccountListQuery);
        return (AccountList.size() > 0) ? AccountList[0] : new Account();
    }

    public static Contact getContactDetails(){
        String ContactListQuery = 'SELECT ' + SYS_Helper.getAllFieldsFor('Contact') +
                ' FROM Contact LIMIT 1';
        List<Contact> ContactList = Database.query(ContactListQuery);
        return (ContactList.size() > 0) ? ContactList[0] : new Contact();
    }

    public static Product__c getProductDetails(){
        String ProductListQuery = 'SELECT ' + SYS_Helper.getAllFieldsFor('Product__c') +
                ', ' + SYS_Helper.getAllParentFields('Account__r.', 'Account') +
                ' FROM Product__c LIMIT 1';
        List<Product__c> ProductList = Database.query(ProductListQuery);
        return (ProductList.size() > 0) ? ProductList[0] : new Product__c();
    }

    public static Google_Calendar__c getGoogleCalendarDetails(){
        String GoogleCalendarListQuery = 'SELECT ' + SYS_Helper.getAllFieldsFor('Google_Calendar__c') +
                ', ' + SYS_Helper.getAllParentFields('Account__r.', 'Account') +
                ', ' + SYS_Helper.getAllParentFields('PMA_Product__r.', 'Product__c') +
                ' FROM Google_Calendar__c LIMIT 1';
        List<Google_Calendar__c> GoogleCalendarList = Database.query(GoogleCalendarListQuery);
        return (GoogleCalendarList.size() > 0) ? GoogleCalendarList[0] : new Google_Calendar__c();
    }

    public static User getUser() {
        String uniqueUserName = 'standarduser' + DateTime.now().getTime() + '@testorg.com';
        // This code runs as the system user
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];
        User u = new User(Alias = 'standt', Email='standarduser@testorg.com',
        EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
        LocaleSidKey='en_US', ProfileId = p.Id,
        TimeZoneSidKey='America/Los_Angeles',
        UserName=uniqueUserName);
        insert u;
        String namespaceprefix = SYS_datacache.namespacePrefix;
        PermissionSet ps = [SELECT Id FROM PermissionSet WHERE Name = 'SYS_Municorn_Permission_Set' AND namespaceprefix =:namespaceprefix ];
        System.debug('user id '+u.id);
        insert new PermissionSetAssignment(AssigneeId = u.id, PermissionSetId = ps.Id);

        return u;
    }
}