force-app/main/default/objects/Account/fields/Plivo_Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Plivo_Country_Code__c</fullName>
    <inlineHelpText>Entered Country Code utilized in all PMA Contacts</inlineHelpText>
    <label>Plivo Country Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Plivo_PHLO_Id__c.field-meta.xml
<CustomField>
    <fullName>Plivo_PHLO_Id__c</fullName>
    <label>Plivo PHLO Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Plivo_Sender_Id__c.field-meta.xml
<CustomField>
    <fullName>Plivo_Sender_Id__c</fullName>
    <inlineHelpText>Plivo Phone Number, shortcode, or Alphanumeric Sender ID.</inlineHelpText>
    <label>Plivo Sender Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Default_Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Default_Payment_Method__c</fullName>
    <inlineHelpText>Default Card or Bank Token</inlineHelpText>
    <label>Default Payment Method</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/StripeCustomerId__c.field-meta.xml
<CustomField>
    <fullName>StripeCustomerId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>StripeCustomerId</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Manager.recordType-meta.xml
<RecordType>
    <fullName>Manager</fullName>
    <active>true</active>
    <description>Portal Users</description>
    <label>Manager</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Member.recordType-meta.xml
<RecordType>
    <fullName>Member</fullName>
    <active>true</active>
    <label>Member</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Vendor.recordType-meta.xml
<RecordType>
    <fullName>Vendor</fullName>
    <active>true</active>
    <description>Portal Users</description>
    <label>Vendor</label>
</RecordType>

force-app/main/default/objects/User/fields/ContactId__c.field-meta.xml
<CustomField>
    <fullName>ContactId__c</fullName>
    <label>ContactId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PortalUserServiceTest.cls
@IsTest
public class PortalUserServiceTest {
    @TestSetup
    static void PortalUserServiceTest() {
            PMA_TestDataFactory.createTestAccountWithContactsRecords(1, 1);
    }
    /*
    @IsTest
    static void createPartnerManagerUserTest(){
        Id MemberRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Member').getRecordTypeId();
        Id ManagerRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Manager').getRecordTypeId();
        
        Contact currentContact = [Select Id,Name,FirstName,LastName,RecordTypeId, Phone_Number__c, Email, Account.Name,RecordType.Name FROM Contact LIMIT 1];
		currentContact.RecordTypeId = ManagerRecordTypeId;
        currentContact.FirstName = 'Test';
        currentContact.LastName = 'ContactPartnerManager';
        currentContact.Email = 'devportalmanageruser@adisols.com';
        update currentContact;
        Test.startTest();        
        PortalUserService.createPartnerUser(currentContact.Id);
        Test.stopTest();
        
        User currentUserRecord = [SELECT ContactId, ContactId__c FROM User WHERE ContactId =: currentContact.Id];
        System.assertEquals(currentContact.Id, currentUserRecord.ContactId);
    }
    
    @IsTest
    static void createPartnerVendorUserTest(){
        Id MemberRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Member').getRecordTypeId();
        Id VendorRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Vendor').getRecordTypeId();
        
        Contact currentContact = [Select Id,Name,FirstName,LastName,RecordTypeId, Phone_Number__c, Email, Account.Name,RecordType.Name FROM Contact LIMIT 1];
		currentContact.RecordTypeId = VendorRecordTypeId;
        currentContact.FirstName = 'Test';
        currentContact.LastName = 'ContactPartnerVendor';
        currentContact.Email = 'devportalVendoruser@adisols.com';
        update currentContact;
        Test.startTest();        
        PortalUserService.createPartnerUser(currentContact.Id);
        Test.stopTest();
        
        User currentUserRecord = [SELECT ContactId, ContactId__c FROM User WHERE ContactId =: currentContact.Id];
        System.assertEquals(currentContact.Id, currentUserRecord.ContactId);
    }
    */
    @IsTest
    static void createManagerSalesforceUserTest(){
        Account account = new Account(Name = 'Sample Account', Plivo_Country_Code__c = '1',
            Plivo_Sender_Id__c = '12222222222', Plivo_PHLO_Id__c = 'Test123');
        insert account;

        SYS_OAuthConfig__c  oauthRecord = PMA_TestDataFactory.createTestSysOauthWithAccessToken(account.Id);
		
        Id ManagerRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Manager').getRecordTypeId();
        Test.startTest();
        Contact contact = new Contact(FirstName = 'Sample', LastName = 'Contact', Email = 'devsfmanager@adisols.com',
            AccountId = account.Id, StripeCustomerId__c = 'cus_G5i0UDob8XanSl', 
            Default_Payment_Method__c = 'card_2JZWVCDQBrpdxQCKwNKVLJq3', RecordTypeId = ManagerRecordTypeId);
        insert contact;
        
        //PortalUserService.createSalesforceUser(contact.Id);
        Test.stopTest();
        User currentUserRecord = [SELECT ContactId, ContactId__c FROM User WHERE ContactId__c =: contact.Id];
        System.assertEquals(contact.Id, currentUserRecord.ContactId__c);
    }
        
}