force-app/main/default/objects/Activity__c/Activity__c.object-meta.xml
<CustomObject>
    <label>PMA Activity</label>
    <nameField>
        <displayFormat>Activity-{0}</displayFormat>
        <label>Activity#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PMA Activities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Activity__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>PMA_Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activity__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>PMA Activities</relationshipLabel>
    <relationshipName>PMA_Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activity__c/fields/Contact_Point__c.field-meta.xml
<CustomField>
    <fullName>Contact_Point__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Point</label>
    <referenceTo>Contact_Point__c</referenceTo>
    <relationshipLabel>PMA Activities</relationshipLabel>
    <relationshipName>PMA_Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activity__c/fields/Direction__c.field-meta.xml
<CustomField>
    <fullName>Direction__c</fullName>
    <label>Direction</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>OUTBOUND</fullName>
            </value>
            <value>
                <fullName>INBOUND</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Activity__c/fields/External_Number__c.field-meta.xml
<CustomField>
    <fullName>External_Number__c</fullName>
    <inlineHelpText>Outbound - From Plivo Number
Inbound - To Plivo Number</inlineHelpText>
    <label>External Number</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Activity__c/fields/HTML_Body__c.field-meta.xml
<CustomField>
    <fullName>HTML_Body__c</fullName>
    <label>HTML Body</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Activity__c/fields/IsInboxMessage__c.field-meta.xml
<CustomField>
    <fullName>IsInboxMessage__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsInboxMessage</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Activity__c/fields/IsUnread__c.field-meta.xml
<CustomField>
    <fullName>IsUnread__c</fullName>
    <defaultValue>true</defaultValue>
    <label>IsUnread</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Activity__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>PMA Activities</relationshipLabel>
    <relationshipName>PMA_Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activity__c/fields/media_url__c.field-meta.xml
<CustomField>
    <fullName>media_url__c</fullName>
    <label>Media URL</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Activity__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Queued</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Undelivered</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Skipped</fullName>
            </value>
            <value>
                <fullName>Replied</fullName>
            </value>
            <value>
                <fullName>ringing</fullName>
                <label>Ringing</label>
            </value>
            <value>
                <fullName>hangup</fullName>
                <label>Hangup</label>
            </value>
            <value>
                <fullName>connected</fullName>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>answer</fullName>
                <label>Answered</label>
            </value>
            <value>
                <fullName>Sending</fullName>
            </value>
            <value>
                <fullName>no-answer</fullName>
                <label>Not Answered</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Activity__c/fields/Text_Body__c.field-meta.xml
<CustomField>
    <fullName>Text_Body__c</fullName>
    <label>Text Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Activity__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>sms</fullName>
            </value>
            <value>
                <fullName>mms</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Call</fullName>
            </value>
            <value>
                <fullName>Recording</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Activity__c/fields/WhatId_ObjectApi_Name__c.field-meta.xml
<CustomField>
    <fullName>WhatId_ObjectApi_Name__c</fullName>
    <label>WhatId ObjectApi Name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <externalId>true</externalId>
    <label>UUID</label>
    <length>250</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact_Point__c/Contact_Point__c.object-meta.xml
<CustomObject>
    <label>Contact Point</label>
    <nameField>
        <displayFormat>CP-{00000}</displayFormat>
        <label>Contact Point Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Points</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Point__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contact Points</relationshipLabel>
    <relationshipName>Contact_Points</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Media_URL__c/Media_URL__c.object-meta.xml
<CustomObject>
    <label>Media Url</label>
    <nameField>
        <displayFormat>MURL-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Media Urls</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Media_URL__c/fields/Activity__c.field-meta.xml
<CustomField>
    <fullName>Activity__c</fullName>
    <label>Activity</label>
    <referenceTo>Activity__c</referenceTo>
    <relationshipLabel>Media Urls</relationshipLabel>
    <relationshipName>Media_Urls</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Media_URL__c/fields/Media_Url__c.field-meta.xml
<CustomField>
    <fullName>Media_Url__c</fullName>
    <label>Media Url</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CustomActivityService.cls
public class CustomActivityService {
    public static Activity__c getActivityByUUID(String uuid){
        List<Activity__c> activityList = new List<Activity__c>(); 
        String activitySearchQuery = 'SELECT ' + SYS_Helper.getAllFieldsFor('Activity__c') +
                ', ' + SYS_Helper.getAllParentFields('Lead__r.', 'Lead') +
                ', ' + SYS_Helper.getAllParentFields('Account__r.', 'Account') +
                ', ' + SYS_Helper.getAllParentFields('Contact__r.', 'Contact') +
                ', ' + SYS_Helper.getAllParentFields('Contact_Point__r.', 'Contact_Point__c') +
                ', ( SELECT ' + SYS_Helper.getAllFieldsFor('Media_URL__c') + ' FROM Media_Urls__r)' +
                ' FROM Activity__c WHERE UUID__c =: uuid ORDER BY When__c DESC ' + 'LIMIT 1';
        activityList = Database.query(activitySearchQuery); 
        return (activityList.size() > 0 ) ? activityList[0] : new Activity__c();
    }

    public static Activity__c getActivityById(Id id) {
        List<Activity__c> activityList = new List<Activity__c>(); 
        String activitySearchQuery = 'SELECT ' + SYS_Helper.getAllFieldsFor('Activity__c') +
                ', ' + SYS_Helper.getAllParentFields('Lead__r.', 'Lead') +
                ', ' + SYS_Helper.getAllParentFields('Account__r.', 'Account') +
                ', ' + SYS_Helper.getAllParentFields('Contact__r.', 'Contact') +
                 ', ' + SYS_Helper.getAllParentFields('Contact_Point__r.', 'Contact_Point__c') +
                ', ( SELECT ' + SYS_Helper.getAllFieldsFor('Media_URL__c') + ' FROM Media_Urls__r)' +
                ' FROM Activity__c WHERE Id =: id  ORDER BY When__c DESC ' + 'LIMIT 1';
        activityList = Database.query(activitySearchQuery); 
        return (activityList.size() > 0 ) ? activityList[0] : new Activity__c();
    }

    //Create Activity with InvokeOutbound flow boolean
    public static Activity__c createActivity(Boolean invokeOutboundFlow, String type, List<String> mediaUrls, String messagebody, String messageSubject,String fromPhone, String toPhone, Id recordId) {
        Id contactId, accountId, leadId = null;
        Activity__c createActivityRecord = createActivity(invokeOutboundFlow, type, mediaUrls, messagebody, messageSubject, fromPhone, toPhone, recordId, accountId);

        return createActivityRecord;
    }

    //Create Activity with AccountBased
    public static Activity__c createActivity(Boolean invokeOutboundFlow, String type, List<String> mediaUrls, String messagebody, String messageSubject,String fromPhone, String toPhone, Id recordId, String accountId) {
        Id contactId, leadId = null;
        String objectApiName = '';
        String mediaurlString = '';
        List<Media_URL__c> mediaUrlList = new List<Media_URL__c>();

        if(recordId != null){    
            objectApiName = recordId.getSObjectType().getDescribe().getName();
            if(objectApiName == 'Contact'){
                contactId = recordId;
            }
            if(objectApiName == 'Account'){
                accountId = recordId;
            }
            if(objectApiName == 'Lead'){
                leadId = recordId;
            }
        } else {
            recordId = null;
        }

        if(mediaUrls.size() > 0){
            mediaurlString = String.join(mediaurls,',');
        }

        Activity__c activityRecord = new Activity__c();
        activityRecord.Type__c = type;
        activityRecord.Direction__c ='OUTBOUND';
        activityRecord.Status__c = 'Queued'; //Sending
        activityRecord.Contact__c = contactId;
        activityRecord.Account__c = accountId;
        activityRecord.Lead__c = leadId;
        activityRecord.WhatId__c = recordId;
        activityRecord.WhatId_ObjectApi_Name__c = objectApiName;
        activityRecord.Subject__c = messageSubject;
        activityRecord.Message__c = messagebody;
        activityRecord.media_url__c = mediaurlString;
        activityRecord.Phone__c = toPhone;
        activityRecord.External_Number__c = fromPhone;
        // activityRecord.Email__c = email;
        activityRecord.IsInboxMessage__c = (invokeOutboundFlow == true) ? false : true;
        activityRecord.Log__c = true;
        activityRecord.Trackable__c = true;
        activityRecord.IsUnread__c = false;
        activityRecord.When__c = System.now();
        insert activityRecord;

        for (String mUrl: mediaurls) {
            Media_URL__c mediaUrl = new Media_URL__c();
            mediaUrl.Media_Url__c = mUrl;
            mediaUrl.Activity__c = activityRecord.Id;
            mediaUrlList.add(mediaUrl);
        }

        if(mediaUrlList.size() > 0){
            insert mediaUrlList;
        }       

        Activity__c createNewActivity = getActivityById(activityRecord.Id);

        return createNewActivity;
    }

    /* creating Email Inbound activity mehtod */
    //Create Activity with AccountBased
    public static Activity__c createEmailActivityLog(Boolean invokeOutboundFlow, String type, string Email,
        string Direction, string status, List < String > mediaUrls,
        String EmailSubject, Id parentrecordId, String accountId, string EmailMessage, string Htmlbody) {
        Id contactId, leadId = null;
        String objectApiName = '';
        String mediaurlString = '';
        List < Media_URL__c > mediaUrlList = new List < Media_URL__c > ();

        if (parentrecordId != null) {
            objectApiName = parentrecordId.getSObjectType().getDescribe().getName();
            if (objectApiName == 'Contact') {
                contactId = parentrecordId;
            }
            if (objectApiName == 'Account') {
                accountId = parentrecordId;
            }
            if (objectApiName == 'Lead') {
                leadId = parentrecordId;
            }
        } else {
            parentrecordId = null;
        }

        if (mediaUrls.size() > 0) {
            mediaurlString = String.join(mediaurls, ',');
        }

        Activity__c activityRecord = new Activity__c();
        activityRecord.Type__c = type;
        activityRecord.Direction__c = Direction;
        activityRecord.Status__c = status; //Sending
        activityRecord.Contact__c = contactId;
        activityRecord.Account__c = accountId;
        activityRecord.Lead__c = leadId;
        activityRecord.WhatId__c = parentrecordId;
        activityRecord.WhatId_ObjectApi_Name__c = objectApiName;
        activityRecord.Subject__c = EmailSubject;
         activityRecord.HTML_Body__c = Htmlbody;
        activityRecord.media_url__c = mediaurlString;
        // activityRecord.Phone__c = toPhone;
        // activityRecord.External_Number__c = fromPhone;
        activityRecord.Email__c = Email;
        activityRecord.IsInboxMessage__c = (invokeOutboundFlow == true) ? false : true;
        activityRecord.Log__c = true;
        activityRecord.Trackable__c = true;
        activityRecord.IsUnread__c = false;
        activityRecord.When__c = System.now();
        activityRecord.Text_Body__c = EmailMessage;
        insert activityRecord;

        for (String mUrl: mediaurls) {
            Media_URL__c mediaUrl = new Media_URL__c();
            mediaUrl.Media_Url__c = mUrl;
            mediaUrl.Activity__c = activityRecord.Id;
            mediaUrlList.add(mediaUrl);
        }

        if (mediaUrlList.size() > 0) {
            insert mediaUrlList;
        }

        Activity__c createNewActivity = getActivityById(activityRecord.Id);

        return createNewActivity;
    }
}