force-app/main/default/objects/Contact/fields/Default_Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Default_Payment_Method__c</fullName>
    <inlineHelpText>Default Card or Bank Token</inlineHelpText>
    <label>Default Payment Method</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/StripeCustomerId__c.field-meta.xml
<CustomField>
    <fullName>StripeCustomerId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>StripeCustomerId</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <externalId>true</externalId>
    <label>UUID</label>
    <length>250</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Member.recordType-meta.xml
<RecordType>
    <fullName>Member</fullName>
    <active>true</active>
    <label>Member</label>
</RecordType>

force-app/main/default/objects/Payment_Intent__c/Payment_Intent__c.object-meta.xml
<CustomObject>
    <label>Payment Intent</label>
    <nameField>
        <label>Payment Intent Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Intents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Intent__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>payment_new</fullName>
                <default>true</default>
                <label>payment_new</label>
            </value>
            <value>
                <fullName>payment_done</fullName>
            </value>
            <value>
                <fullName>payment_expired</fullName>
            </value>
            <value>
                <fullName>payment_failed</fullName>
            </value>
            <value>
                <fullName>canceled</fullName>
            </value>
            <value>
                <fullName>requires_payment_method</fullName>
            </value>
            <value>
                <fullName>succeeded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <label>Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/TransactionServiceTest.cls
@IsTest
public class TransactionServiceTest {
	private static TransactionService transactionService = new TransactionService();
	private static StripeService stripeService = new StripeService();
    
    @TestSetup
    static void TransactionServiceTest() {
            PMA_TestDataFactory.createTestAccountWithContactsRecords(1, 1);
    }  
    
    @IsTest
    static void createTransactionTest(){
        Account account = new Account(Name = 'Sample Account');
        insert account;
	
        SYS_OAuthConfig__c  oauthRecord = PMA_TestDataFactory.createTestSysOauthWithAccessToken(account.Id);

        Id MemberRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Member').getRecordTypeId();
        
        Contact contact = new Contact(FirstName = 'Sample', LastName = 'Contact', AccountId = account.Id,StripeCustomerId__c = 'cus_G5i0UDob8XanSl',Default_Payment_Method__c = 'card_2JZWVCDQBrpdxQCKwNKVLJq3',RecordTypeId = MemberRecordTypeId);
        insert contact;

        Payment_Intent__c paymentRequest = PaymentIntentService.createNewPaymentIntent(
                'Test Payment Request',
                contact.Id,
                account.Id,
                null,
                'immediate',
                Double.valueOf(23.4),
                'sample@gmail.com',
                'single',
                System.TODAY());
        Transaction__c txn = transactionService.createTransaction(paymentRequest);
        txn.StripeChargeId__c = 'ch_1FWEhYDQBrpdxQCKCGLUUXsP';
        txn.UUID__c = 'MDa3wwxOad5TpQHaNH9k9XCgUgXhQXa';
        txn.Status__c = 'succeeded';
        update txn;
        Transaction__c fetchtxn = transactionService.getTransactionByChargeId(txn.StripeChargeId__c);
        System.assertEquals('MDa3wwxOad5TpQHaNH9k9XCgUgXhQXa', fetchtxn.UUID__c);
        System.assertEquals('ch_1FWEhYDQBrpdxQCKCGLUUXsP', fetchtxn.StripeChargeId__c);
    }
    
    @IsTest
    static void getTransactionByUuidTest(){
        Account account = new Account(Name = 'Sample Account');
        insert account;

        SYS_OAuthConfig__c  oauthRecord = PMA_TestDataFactory.createTestSysOauthWithAccessToken(account.Id);
		
        Id MemberRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Member').getRecordTypeId();
        
        Contact contact = new Contact(FirstName = 'Sample', LastName = 'Contact', AccountId = account.Id,StripeCustomerId__c = 'cus_G5i0UDob8XanSl',Default_Payment_Method__c = 'card_2JZWVCDQBrpdxQCKwNKVLJq3',RecordTypeId = MemberRecordTypeId);
        insert contact;

        Payment_Intent__c paymentRequest = PaymentIntentService.createNewPaymentIntent(
                'Test Payment Request',
                contact.Id,
                account.Id,
                null,
                'immediate',
                Double.valueOf(23.4),
                'sample@gmail.com',
                'single',
                System.TODAY());
        Transaction__c txn = transactionService.createTransaction(paymentRequest);
        txn.StripeChargeId__c = 'ch_1FWEhYDQBrpdxQCKCGLUUXsP';
        txn.UUID__c = 'MDa3wwxOad5TpQHaNH9k9XCgUgXhQXa';
        txn.Status__c = 'succeeded';
        update txn;
        Transaction__c fetchtxn = transactionService.getTransactionByUuid(txn.UUID__c);
        System.assertEquals('MDa3wwxOad5TpQHaNH9k9XCgUgXhQXa', fetchtxn.UUID__c);
        System.assertEquals('ch_1FWEhYDQBrpdxQCKCGLUUXsP', fetchtxn.StripeChargeId__c);
    }
    
}