force-app/main/default/objects/Contact/fields/Gsheetsync__c.field-meta.xml
<CustomField>
    <fullName>Gsheetsync__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Gsheetsync</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SpreadSheet__c.field-meta.xml
<CustomField>
    <fullName>SpreadSheet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SpreadSheet</label>
    <referenceTo>SpreadSheet__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SpreadSheet_Id__c.field-meta.xml
<CustomField>
    <fullName>SpreadSheet_Id__c</fullName>
    <formula>SpreadSheet__r.SpreadSheet_Id__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SpreadSheet Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SpreadSheet__c/SpreadSheet__c.object-meta.xml
<CustomObject>
    <label>SpreadSheet</label>
    <nameField>
        <label>SpreadSheet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SpreadSheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SpreadSheet__c/fields/SpreadSheet_Id__c.field-meta.xml
<CustomField>
    <fullName>SpreadSheet_Id__c</fullName>
    <externalId>true</externalId>
    <label>SpreadSheet Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/G_sheetsoldrecordprocesser.cls
public with sharing class G_sheetsoldrecordprocesser implements Database.Batchable < sObject > , Database.Stateful, Database.AllowsCallouts,schedulable {

  public List < Id > AccountIdlist;
  public Integer accountCount;
  public Id AccountId;
  public G_sheetsoldrecordprocesser(List < Id > AccountIdlist) {
    this.AccountIdlist = AccountIdlist;
    this.accountCount = AccountIdlist.size();
  }
  public Database.QueryLocator start(Database.BatchableContext BC) {
    //String accountId = '001Hp00002kZNupIAG';
    Id accid = AccountIdlist[0];
    String type = 'SpreadSheet';
    SYS_DataCacheFactory init = new SYS_DataCacheFactory(
      accid,
      type,
      type,
      'object_api_name');
      string ObjectApiName = 'Contact';
    String query = 'SELECT ' + SYS_Helper.getAllFieldsFor(ObjectApiName) + '  FROM  ' + ObjectApiName;
    String whereClause = ' WHERE AccountId in (' + '\'' + String.escapeSingleQuotes(accid) + '\')';
   // List < Sobject > sobjectrecList = Database.query(String.escapeSingleQuotes(query) + whereClause);
    //string orderedfields = SYS_DataCacheFactory.metadata.get('object_api_name');
   // String query = 'SELECT id,SpreadSheet_Id__c,SpreadSheet__c from Contact';
    system.debug('queryContact' + query);
    return Database.getQueryLocator(String.escapeSingleQuotes(query) + whereClause);
  }
  public void execute(Database.BatchableContext BC, List < Contact > sojectlist) {
    string Gsheetid = G_sheetsoldrecordprocesserhandler.Spreadsheetid(sojectlist);
    string accountId = AccountIdlist[0];

    // if(){
    //  string  = G_sheetsoldrecordprocesserhandler.spreadsheetCreation(accountId);
    //}
    string responsebody = G_sheetsoldrecordprocesserhandler.Clearsheet(Gsheetid, accountId);
    system.debug('Gsheetid' + Gsheetid);
    for (Contact sobj: sojectlist) {
      sobj.SpreadSheet__c = Gsheetid;
      sobj.Gsheetsync__c = false;
    }
    update sojectlist;
  }
  //Schedulable Excute
  public void execute(SchedulableContext SC) {
    List < Id > accidList = new List < Id > ();
    List < Account > AccountIdlist = [SELECT ID from Account];
    for (Account Accountid: AccountIdlist) {
      accidList.add(Accountid.Id);

    }
    accidList.remove(0);
    for (Integer i = 0, j = 0; i < accidList.size(); i++) {
      database.executebatch(new G_sheetsoldrecordprocesser(accidList));
    }

  }

  public void finish(Database.BatchableContext BC) {
   

  }
}