force-app/main/default/objects/Contact/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <externalId>true</externalId>
    <label>UUID</label>
    <length>250</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Custom_Form__c/Custom_Form__c.object-meta.xml
<CustomObject>
    <label>Custom Form</label>
    <nameField>
        <displayFormat>F-{00000000}</displayFormat>
        <label>Custom Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Custom Forms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Custom_Form__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Custom Forms</relationshipLabel>
    <relationshipName>Custom_Forms</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Custom_Form__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Custom Forms</relationshipLabel>
    <relationshipName>Custom_Forms</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Custom_Form__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Custom Forms</relationshipLabel>
    <relationshipName>Custom_Forms</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Custom_Form__c/fields/Survey__c.field-meta.xml
<CustomField>
    <fullName>Survey__c</fullName>
    <label>Survey</label>
    <referenceTo>Survey__c</referenceTo>
    <relationshipLabel>Custom Forms</relationshipLabel>
    <relationshipName>Custom_Forms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Survey__c/Survey__c.object-meta.xml
<CustomObject>
    <description>Survey Force object</description>
    <label>Survey</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/SF_GenerateSurveyLinkInvocable.cls
public without sharing class SF_GenerateSurveyLinkInvocable {
    

    public class VariableBucket {
        @InvocableVariable(label='Contact Id' description= 'Fill either contact or account or lead Id.' required=false)  
        public Id contactId;
    
        @InvocableVariable(label='Account Id' description= 'Fill either contact or account or lead Id.' required=false)  
        public Id accountId;

        @InvocableVariable(label='Lead Id' description= 'Fill either contact or account or lead Id.' required=false)  
        public Id leadId;

        @InvocableVariable(label='Survey Id' description= 'Fill the survey Id need to be used.' required=true)  
        public Id surveyId;
    }

    @InvocableMethod(label='Capture Request for Outbound' description='To capture outbound request and create a SYS_IntegrationLog record for Municorn')
    public static List<Custom_Form__c> generateSurveyLink(List<VariableBucket> requestList) {
        List<Custom_Form__c> formList = new List<Custom_Form__c>();

        if(requestList.size() == 0) return formList;
        try {
            
            for(VariableBucket item: requestList) {
                Custom_Form__c form = new Custom_Form__c();
                form.uuid__c = SYS_Helper.getUUID();
                form.Account__c = item.accountId;
                form.Contact__c = item.contactId;
                form.Lead__c = item.leadId;
                form.Survey__c = item.surveyId;
    
                formList.add(form);
            }
    
            insert formList;
        } catch(Exception e) {
            throw new SF_GenerateSurveyLinkInvocableException('Error occured while creating custom survey form \n'+ e.getMessage());
        }
        return formList;
        
    }


    public class SF_GenerateSurveyLinkInvocableException extends Exception{}
}