force-app/main/default/objects/Action_Parameter__c/Action_Parameter__c.object-meta.xml
<CustomObject>
    <label>Action Parameter</label>
    <nameField>
        <label>Action Parameter Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Action Parameter</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Action_Parameter__c/fields/VisualForce_Page__c.field-meta.xml
<CustomField>
    <fullName>VisualForce_Page__c</fullName>
    <label>VisualForce Page</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UUID_Tracker__c/UUID_Tracker__c.object-meta.xml
<CustomObject>
    <label>UUID Tracker</label>
    <nameField>
        <displayFormat>T-{00000}</displayFormat>
        <label>UUID Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UUID Trackers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UUID_Tracker__c/fields/Action_Parameter__c.field-meta.xml
<CustomField>
    <fullName>Action_Parameter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Action Parameter</label>
    <referenceTo>Action_Parameter__c</referenceTo>
    <relationshipLabel>UUID Trackers</relationshipLabel>
    <relationshipName>UUID_Trackers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UUID_Tracker__c/fields/No_Of_Clicks__c.field-meta.xml
<CustomField>
    <fullName>No_Of_Clicks__c</fullName>
    <defaultValue>0</defaultValue>
    <label>No Of Clicks</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/RouterController.cls
public without sharing class RouterController {
    public String uuid { get; set; }
    public String error { get; set; }
    public String redirectUrl { get; set; }

    public RouterController() {

    }

    public class RouterControllerException extends Exception {}

    public PageReference routerInit() {
        PageReference returnURL;
        try {
            this.uuid = System.currentPageReference().getParameters().get('uuid');
            System.debug('uuid value '+this.uuid);
            UUID_Tracker__c tracker = getTrackerrecord(this.uuid);

            String vfpage = tracker.Action_Parameter__r.VisualForce_Page__c;
            System.debug('vfpage '+vfpage);
            returnURL = redirectUrl(vfpage, this.uuid);

            tracker.No_Of_Clicks__c += 1;
            update tracker;

        } catch (Exception e) {
            System.debug(e.getMessage()+'\n'+e.getStackTraceString());
        }
        return returnURL;
    }

    public PageReference redirectUrl(String vfpage, String uuid) {
        PageReference pageRef = new PageReference(Site.getBaseSecureUrl()+'/apex/'+vfpage);
        pageRef.getParameters().put('uuid',uuid);
        pageRef.setRedirect(true);

        // return new PageReference('http://www.google.com');
        return pageRef;
    }

    public UUID_Tracker__c getTrackerRecord(String value) {
        UUID_Tracker__c tracker;
        try {
            String query = 'SELECT ' + + UUIDHelper.getAllFieldsFor('UUID_Tracker__c') + 
                +', '+ UUIDHelper.getAllParentFields('Action_Parameter__r.', 'Action_Parameter__c') +
                ' FROM UUID_Tracker__c WHERE UUID__c = :value LIMIT 1';
            tracker = Database.query(query);

        } catch ( Exception e ) {
            throw new RouterControllerException(e.getMessage()+'\n'+e.getStackTraceString());
        }
        return tracker;
    }
}