force-app/main/default/objects/Action_Parameter__c/Action_Parameter__c.object-meta.xml
<CustomObject>
    <label>Action Parameter</label>
    <nameField>
        <label>Action Parameter Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Action Parameter</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Action_Parameter__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <label>Site</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Action_Parameter__c/fields/Site_URL__c.field-meta.xml
<CustomField>
    <fullName>Site_URL__c</fullName>
    <label>Site URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Action_Parameter__c/fields/VisualForce_Page__c.field-meta.xml
<CustomField>
    <fullName>VisualForce_Page__c</fullName>
    <label>VisualForce Page</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Action_Parameter__c/fields/VisualForce_Page_Id__c.field-meta.xml
<CustomField>
    <fullName>VisualForce_Page_Id__c</fullName>
    <label>VisualForce Page Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ActionParameterSetupController.cls
public with sharing class ActionParameterSetupController {
    public ActionParameterSetupController() {

    }

    @AuraEnabled
    public static void sample(String recordId, String objectWrapper) {
        try {
            System.debug(recordId + objectWrapper);
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static void updateActionParameterSite(String recordId, String objectWrapper) {
        try {
            System.debug(recordId + objectWrapper);
            Map<String, Object> siteInfo = ((Map<String, Object>)JSON.deserializeUntyped(objectWrapper));
            String siteId = (String)siteInfo.get('Id');
            SiteDetail mySiteDetail = [SELECT SecureURL FROM SiteDetail WHERE DurableId = :siteId];
            
            Action_Parameter__c parameter = new Action_Parameter__c(Id = recordId);
            parameter.Site__c = siteId;
            parameter.Site_Name__c = (String)siteInfo.get('Name');
            parameter.Site_URL__c = mySiteDetail.SecureURL;

            update parameter;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static void updateActionParameterPage(String recordId, String objectWrapper) {
        try {
            Map<String, Object> pageInfo = ((Map<String, Object>)JSON.deserializeUntyped(objectWrapper));

            Action_Parameter__c parameter = new Action_Parameter__c(Id = recordId);
            parameter.VisualForce_Page__c = (String)pageInfo.get('Name');
            parameter.VisualForce_Page_Id__c = (String)pageInfo.get('Id');
            update parameter;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}