force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>PMA Order</label>
    <nameField>
        <displayFormat>O-{00000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PMA Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Draft&quot;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/EstimateControllerTest.cls
@IsTest
public with sharing class EstimateControllerTest {
    @TestSetup
    static void EstimateControllerTest(){
        PMA_TestDataFactory.createTestAccountWithContactsRecords(1, 3);  
    }
    @IsTest
    static void EstimateOrderdataTest() {
        Account getcurrAccount = PMA_TestDataFactory.getTestAccountWithContactsRecords();
        List<Contact> fetchContact = getcurrAccount.Contacts;
        System.debug('fetchContact test ' + fetchContact);
        for(Contact con : fetchContact){
        	PMA_TestDataFactory.createTestOrderRecords(getcurrAccount.Id, con.Id,'Estimate');
        }
        Order__c fetchOrder = PMA_TestDataFactory.getTestOrderwithOrderItemRecords();

        EstimateController estmate = new EstimateController();
        estmate.memberrecordid = fetchContact[0].Id;
        estmate.EstimateOrderdata();
       System.assertEquals('Estimate', fetchOrder.Status__c);
    }
    @IsTest
    static void EstimateOrderdataCancelTest() {
        Account getcurrAccount = PMA_TestDataFactory.getTestAccountWithContactsRecords();
        List<Contact> fetchContact = getcurrAccount.Contacts;
        System.debug('fetchContact test ' + fetchContact);
        for(Contact con : fetchContact){
        	PMA_TestDataFactory.createTestOrderRecords(getcurrAccount.Id, con.Id,'Estimate');
        }
        Order__c fetchOrder = PMA_TestDataFactory.getTestOrderwithOrderItemRecords();
       
        EstimateController estmate = new EstimateController();
        estmate.orderdata = fetchOrder;
        estmate.cancelOrderdata();
        Order__C order = [SELECT Status__c from Order__c where Id =:fetchOrder.Id];
        System.assertEquals('Cancelled', order.Status__c);
        
    }
}